/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Distribution;

/**
 *
 * @author Bhanu
 */
import static java.lang.Thread.sleep;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Statement;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import javafx.scene.control.Alert;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.SwingUtilities;
import javax.swing.ButtonGroup;




public class Distribution extends javax.swing.JFrame {

    
    /**
     * Creates new form Distribution
     */
    public Distribution() {
        initComponents();
    }
    private static Connection con;
     private static void dbConnect()
    {
        try
        {
            Class.forName("com.mysql.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/ManagementSystem", "root", "1234");
        }
        catch(ClassNotFoundException ce)
        {
            Alert alert = new Alert(Alert.AlertType.ERROR);
            alert.setTitle("Error");
            alert.setHeaderText("Database Driver Error");
            alert.setContentText("Unable to load the database driver.");
            alert.showAndWait();
        }
        catch(SQLException se)
        {
            Alert alert = new Alert(Alert.AlertType.ERROR);
            alert.setTitle("Error");
            alert.setHeaderText("Database Connection Error");
            alert.setContentText("Unable to connect to the database.");
            alert.showAndWait();
        }
    }
    public class TimerThread extends Thread
    {
        private JLabel time;
        private boolean running;
        private SimpleDateFormat timeFormat = new SimpleDateFormat("h:mm a");
        
        public TimerThread(JLabel time)
        {
            this.time = time;
            running = true;
        }
        
        public void setRunning(boolean running)
        {
            this.running = running;
        }
        
        public void run()
        {
            while(running)
            {
                SwingUtilities.invokeLater(() -> {
                    time.setText(timeFormat.format(Calendar.getInstance().getTime()));
                });
                try
                {
                    sleep(1000);
                }
                catch(InterruptedException e){}
            }
        }
    }
    
    private String getDate()
    {
        Calendar cal = Calendar.getInstance();
        return cal.get(Calendar.DATE)+" "+getMonth()+" "+cal.get(Calendar.YEAR);
    }
    private int getDay()
    {
        return Calendar.getInstance().get(Calendar.DATE);
    }
    
    private int getYear()
    {
        return Calendar.getInstance().get(Calendar.YEAR);
    }
    
    private static String getMonth()
    {
        String months[] = {"January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December"};
        return months[Calendar.getInstance().get(Calendar.MONTH)];
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        topbar = new javax.swing.JPanel();
        close = new javax.swing.JLabel();
        minimize = new javax.swing.JLabel();
        time = new javax.swing.JLabel();
        date = new javax.swing.JLabel();
        center = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jLabel27 = new javax.swing.JLabel();
        jTextField19 = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jTextField20 = new javax.swing.JTextField();
        jTextField21 = new javax.swing.JTextField();
        jTextField22 = new javax.swing.JTextField();
        jTextField23 = new javax.swing.JTextField();
        jTextField31 = new javax.swing.JTextField();
        jLabel41 = new javax.swing.JLabel();
        save_btn = new javax.swing.JButton();
        cancel_btn = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jLabel32 = new javax.swing.JLabel();
        jTextField24 = new javax.swing.JTextField();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jTextField25 = new javax.swing.JTextField();
        jTextField26 = new javax.swing.JTextField();
        jTextField27 = new javax.swing.JTextField();
        jTextField28 = new javax.swing.JTextField();
        jLabel37 = new javax.swing.JLabel();
        jTextField29 = new javax.swing.JTextField();
        jLabel38 = new javax.swing.JLabel();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jLabel39 = new javax.swing.JLabel();
        jTextField30 = new javax.swing.JTextField();
        jTextField1 = new javax.swing.JTextField();
        jLabel40 = new javax.swing.JLabel();
        save_btn1 = new javax.swing.JButton();
        cancel_btn1 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        topbar.setBackground(new java.awt.Color(0, 204, 204));
        topbar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        close.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Distribution/images/icons8_Close_Window_40px.png"))); // NOI18N
        close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeMouseClicked(evt);
            }
        });
        topbar.add(close, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 0, -1, 49));

        minimize.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Distribution/images/icons8_Minimize_Window_40px.png"))); // NOI18N
        minimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minimizeMouseClicked(evt);
            }
        });
        topbar.add(minimize, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 0, -1, 50));

        time.setText("Time");
        topbar.add(time, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 0, 120, 50));

        date.setText("Date with calender");
        topbar.add(date, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 0, 130, 50));

        getContentPane().add(topbar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 1080, -1));

        center.setBackground(new java.awt.Color(199, 238, 238));
        center.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(0, 204, 204));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("  Add Vendor Details");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 50));

        center.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 500, 50));

        jPanel1.setBackground(new java.awt.Color(187, 237, 211));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel8.setBackground(new java.awt.Color(100, 199, 150));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel27.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel27.setText("Vendor Name");
        jPanel8.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 110, 30));

        jTextField19.setText("           ");
        jPanel8.add(jTextField19, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 60, 220, 25));

        jLabel28.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel28.setText("Address");
        jPanel8.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 110, 30));

        jLabel29.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel29.setText("Email ");
        jPanel8.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 110, 30));

        jLabel30.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel30.setText("Phone Number");
        jPanel8.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 150, 30));

        jLabel31.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel31.setText("Shipping Costs");
        jPanel8.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 150, 30));

        jTextField20.setText("           ");
        jTextField20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField20ActionPerformed(evt);
            }
        });
        jPanel8.add(jTextField20, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 100, 220, 25));

        jTextField21.setText("           ");
        jPanel8.add(jTextField21, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 150, 220, 25));

        jTextField22.setText("           ");
        jTextField22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField22ActionPerformed(evt);
            }
        });
        jPanel8.add(jTextField22, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 200, 220, 25));

        jTextField23.setText("           ");
        jPanel8.add(jTextField23, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 250, 220, 25));

        jTextField31.setText("           ");
        jPanel8.add(jTextField31, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 20, 220, 25));

        jLabel41.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel41.setText("Vendor ID");
        jPanel8.add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 110, 30));

        jPanel1.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 460, 320));

        save_btn.setBackground(new java.awt.Color(71, 179, 71));
        save_btn.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        save_btn.setText("  Save");
        save_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                save_btnActionPerformed(evt);
            }
        });
        jPanel1.add(save_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 350, 150, 40));

        cancel_btn.setBackground(new java.awt.Color(71, 179, 71));
        cancel_btn.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        cancel_btn.setText("Clear");
        cancel_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancel_btnActionPerformed(evt);
            }
        });
        jPanel1.add(cancel_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 350, 150, 40));

        center.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 500, 430));

        jPanel2.setBackground(new java.awt.Color(187, 237, 211));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel9.setBackground(new java.awt.Color(100, 199, 150));
        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel32.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel32.setText("Shipping ID");
        jPanel9.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 110, 30));

        jTextField24.setText("           ");
        jPanel9.add(jTextField24, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 90, 220, 25));

        jLabel33.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel33.setText("Date");
        jPanel9.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 110, 30));

        jLabel34.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel34.setText("Time Taken");
        jPanel9.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 110, 30));

        jLabel35.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel35.setText("Shipping Costs");
        jPanel9.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 150, 30));

        jLabel36.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel36.setText("Item ID");
        jPanel9.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, 150, 30));

        jTextField25.setText("           ");
        jPanel9.add(jTextField25, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 140, 220, 25));

        jTextField26.setText("           ");
        jPanel9.add(jTextField26, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 180, 220, 25));

        jTextField27.setText("           ");
        jTextField27.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField27ActionPerformed(evt);
            }
        });
        jPanel9.add(jTextField27, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 220, 220, 25));

        jTextField28.setText("           ");
        jPanel9.add(jTextField28, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 270, 220, 25));

        jLabel37.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel37.setText("Quantity");
        jPanel9.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, 150, 30));

        jTextField29.setText("           ");
        jPanel9.add(jTextField29, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 310, 220, 30));

        jLabel38.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel38.setText("Type");
        jPanel9.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, 150, 30));

        jRadioButton3.setBackground(new java.awt.Color(100, 199, 150));
        jRadioButton3.setText("Vendor");
        jRadioButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton3ActionPerformed(evt);
            }
        });
        jPanel9.add(jRadioButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 350, -1, -1));

        jRadioButton4.setBackground(new java.awt.Color(100, 199, 150));
        jRadioButton4.setText("Retailer");
        jRadioButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton4ActionPerformed(evt);
            }
        });
        jPanel9.add(jRadioButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 350, -1, -1));

        jLabel39.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel39.setText("Cost");
        jPanel9.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 390, 150, 30));

        jTextField30.setText("           ");
        jPanel9.add(jTextField30, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 390, 220, 25));
        jPanel9.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 30, 220, 30));

        jLabel40.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel40.setText("Vendor ID");
        jPanel9.add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 110, 30));

        jPanel2.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 460, 430));

        save_btn1.setBackground(new java.awt.Color(71, 179, 71));
        save_btn1.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        save_btn1.setText("  Save");
        save_btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                save_btn1ActionPerformed(evt);
            }
        });
        jPanel2.add(save_btn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 460, 150, 40));

        cancel_btn1.setBackground(new java.awt.Color(71, 179, 71));
        cancel_btn1.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        cancel_btn1.setText("Clear");
        cancel_btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancel_btn1ActionPerformed(evt);
            }
        });
        jPanel2.add(cancel_btn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 460, 150, 40));

        jButton4.setBackground(new java.awt.Color(100, 199, 150));
        jButton4.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jButton4.setText("Calculate");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 460, 150, 40));

        center.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 50, 500, 520));

        jPanel4.setBackground(new java.awt.Color(0, 204, 204));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Register Shipping");
        jPanel4.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 400, 50));

        center.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 0, 500, -1));

        jTable1.setBackground(new java.awt.Color(100, 199, 150));
        jTable1.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Name", "Date", "Time", "Shipping Cost", "Item", "Quantity", "Type", "Cost"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Float.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.Float.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable1.setGridColor(new java.awt.Color(255, 255, 255));
        jScrollPane1.setViewportView(jTable1);

        center.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 580, 1010, 130));

        getContentPane().add(center, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 1080, 754));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    
    
    private void closeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMouseClicked
        System.exit(0); // cancel button
    }//GEN-LAST:event_closeMouseClicked

    private void minimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizeMouseClicked
        //minimize label
        this.setExtendedState(JFrame.ICONIFIED);
    }//GEN-LAST:event_minimizeMouseClicked

    private void jTextField22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField22ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField22ActionPerformed

    private void save_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_save_btnActionPerformed
        if(con == null)
            dbConnect();
        
        String Vname = jTextField19.getText();
        String VID = jTextField31.getText();
        String Address = jTextField20.getText();
        String Email = jTextField21.getText();
        String Phone = jTextField22.getText();
        String ship_cost = jTextField23.getText();
        try
        {
        Statement add_vendor = con.createStatement();
         Alert alert = new Alert(Alert.AlertType.INFORMATION);
         alert.setTitle("Success");
         add_vendor.executeQuery("Insert into Vendor values('"+VID+"','"+Vname+"','"+Address+"','"+Email+"','"+Phone+"','"+ship_cost+"')");
         alert.setHeaderText("Insertion successful");
         alert.setContentText("The financial report for the current month and year has been inserted.");
         alert.getDialogPane().setPrefSize(400, 200);
         alert.showAndWait();
        }
        catch(SQLException se)
        {
            Alert alert = new Alert(Alert.AlertType.ERROR);
            alert.setTitle("Error");
            alert.setHeaderText("Database Insert Error");
            alert.setContentText("Unable to Insert into DB");
            alert.showAndWait();
        }
    }//GEN-LAST:event_save_btnActionPerformed

    private void cancel_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancel_btnActionPerformed
        jTextField19.setText("");
        jTextField20.setText("");
        jTextField21.setText("");
        jTextField22.setText("");
        jTextField23.setText("");
        jTextField31.setText("");
    }//GEN-LAST:event_cancel_btnActionPerformed

    private void jTextField27ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField27ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField27ActionPerformed

    private void save_btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_save_btn1ActionPerformed
        if(con == null)
            dbConnect();
        String SID = jTextField1.getText();
        String VID = jTextField24.getText();
        String Date = jTextField25.getText();
        String ship_cost = jTextField27.getText();
        String item = jTextField28.getText();
        String qty = jTextField29.getText();
        String cost = jTextField30.getText();
        String type;
        if(jRadioButton3.isSelected())
            type = "Vendor";
        else
            type="Retailer";
        try
        {
        Statement add_ship = con.createStatement( );
        ResultSet rsb = add_ship.executeQuery("Insert into Shipping_Rec values('"+VID+"','"+SID+"','"+Date+"','"+ship_cost+",'"+type+"')");
        ResultSet rsc = add_ship.executeQuery("Insert into Distribution_Item('"+item+"','"+qty+"','"+cost+"')");
        }
        catch(SQLException se)
        {
            Alert alert = new Alert(Alert.AlertType.ERROR);
            alert.setTitle("Error");
            alert.setHeaderText("Database Insert Error");
            alert.setContentText("Unable to Insert into DB");
            alert.showAndWait();
        }
    }//GEN-LAST:event_save_btn1ActionPerformed

    private void cancel_btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancel_btn1ActionPerformed
        jTextField24.setText("");
        jTextField25.setText("");
        jTextField26.setText("");
        jTextField27.setText("");
        jTextField28.setText("");
        jTextField29.setText("");
        jTextField30.setText("");
        jTextField1.setText("");
        jRadioButton3.setSelected(false);
        jRadioButton4.setSelected(false);
    }//GEN-LAST:event_cancel_btn1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        if(con == null)
            dbConnect();
        String VID = jTextField24.getText();
        int timetaken = Integer.parseInt(jTextField26.getText());
        String item=jTextField28.getText();
        try
        {
        Statement stmt1 = con.createStatement( );
        ResultSet rsd = stmt1.executeQuery("select shipping_cost_ph from Vendor where vendor_ID='"+VID+"'");
        int c = rsd.getInt("Shipping_Cost_ph");
        jTextField27.setText(Integer.toString(c*timetaken));
        ResultSet a = stmt1.executeQuery("select price from Stock where item_ID='"+item+"'");
        int price = a.getInt("price");
        jTextField30.setText(Integer.toString(price*Integer.parseInt(jTextField29.getText())));
        }
        catch(SQLException se)
        {
            Alert alert = new Alert(Alert.AlertType.ERROR);
            alert.setTitle("Error");
            alert.setHeaderText("Database Retrieve Error");
            alert.setContentText("Unable to Retrieve into DB");
            alert.showAndWait();
        }
        
        
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jTextField20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField20ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField20ActionPerformed

    private void jRadioButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton4ActionPerformed

    private void jRadioButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton3ActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
       
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Distribution.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Distribution().setVisible(true);
        });
    }

    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancel_btn;
    private javax.swing.JButton cancel_btn1;
    private javax.swing.JPanel center;
    private javax.swing.JLabel close;
    private javax.swing.JLabel date;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField19;
    private javax.swing.JTextField jTextField20;
    private javax.swing.JTextField jTextField21;
    private javax.swing.JTextField jTextField22;
    private javax.swing.JTextField jTextField23;
    private javax.swing.JTextField jTextField24;
    private javax.swing.JTextField jTextField25;
    private javax.swing.JTextField jTextField26;
    private javax.swing.JTextField jTextField27;
    private javax.swing.JTextField jTextField28;
    private javax.swing.JTextField jTextField29;
    private javax.swing.JTextField jTextField30;
    private javax.swing.JTextField jTextField31;
    private javax.swing.JLabel minimize;
    private javax.swing.JButton save_btn;
    private javax.swing.JButton save_btn1;
    private javax.swing.JLabel time;
    private javax.swing.JPanel topbar;
    // End of variables declaration//GEN-END:variables
private TimerThread timer;
}
