/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package itpshnew;

/**
 *
 * @author Bhanu
 */
import static java.lang.Thread.sleep;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.SwingUtilities;

public class Distribution extends javax.swing.JFrame {

    /**
     * Creates new form Distribution
     */
    public Distribution() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        topbar = new javax.swing.JPanel();
        close = new javax.swing.JLabel();
        minimize = new javax.swing.JLabel();
        time = new javax.swing.JLabel();
        date = new javax.swing.JLabel();
        sidepanel = new javax.swing.JPanel();
        topic1 = new javax.swing.JPanel();
        bar1 = new javax.swing.JPanel();
        name = new javax.swing.JLabel();
        pic = new javax.swing.JLabel();
        topic2 = new javax.swing.JPanel();
        bar2 = new javax.swing.JPanel();
        name1 = new javax.swing.JLabel();
        pic1 = new javax.swing.JLabel();
        topic3 = new javax.swing.JPanel();
        bar3 = new javax.swing.JPanel();
        name2 = new javax.swing.JLabel();
        pic2 = new javax.swing.JLabel();
        topic4 = new javax.swing.JPanel();
        bar4 = new javax.swing.JPanel();
        name3 = new javax.swing.JLabel();
        pic3 = new javax.swing.JLabel();
        topic5 = new javax.swing.JPanel();
        bar5 = new javax.swing.JPanel();
        name4 = new javax.swing.JLabel();
        pic4 = new javax.swing.JLabel();
        topic6 = new javax.swing.JPanel();
        bar6 = new javax.swing.JPanel();
        name5 = new javax.swing.JLabel();
        pic5 = new javax.swing.JLabel();
        topic7 = new javax.swing.JPanel();
        bar7 = new javax.swing.JPanel();
        name6 = new javax.swing.JLabel();
        pic6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator1 = new javax.swing.JSeparator();
        topic8 = new javax.swing.JPanel();
        bar8 = new javax.swing.JPanel();
        name7 = new javax.swing.JLabel();
        pic7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        center = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jLabel27 = new javax.swing.JLabel();
        jTextField19 = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jTextField20 = new javax.swing.JTextField();
        jTextField21 = new javax.swing.JTextField();
        jTextField22 = new javax.swing.JTextField();
        jTextField23 = new javax.swing.JTextField();
        save_btn = new javax.swing.JButton();
        cancel_btn = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jLabel32 = new javax.swing.JLabel();
        jTextField24 = new javax.swing.JTextField();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jTextField25 = new javax.swing.JTextField();
        jTextField26 = new javax.swing.JTextField();
        jTextField27 = new javax.swing.JTextField();
        jTextField28 = new javax.swing.JTextField();
        jLabel37 = new javax.swing.JLabel();
        jTextField29 = new javax.swing.JTextField();
        jLabel38 = new javax.swing.JLabel();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jLabel39 = new javax.swing.JLabel();
        jTextField30 = new javax.swing.JTextField();
        save_btn1 = new javax.swing.JButton();
        cancel_btn1 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        topbar.setBackground(new java.awt.Color(0, 204, 204));
        topbar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        close.setIcon(new javax.swing.ImageIcon(getClass().getResource("/itpshnew/images/icons8_Close_Window_40px.png"))); // NOI18N
        close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeMouseClicked(evt);
            }
        });
        topbar.add(close, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 0, -1, 49));

        minimize.setIcon(new javax.swing.ImageIcon(getClass().getResource("/itpshnew/images/icons8_Minimize_Window_40px.png"))); // NOI18N
        minimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minimizeMouseClicked(evt);
            }
        });
        topbar.add(minimize, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 0, -1, 50));

        time.setText("Time");
        topbar.add(time, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 0, 120, 50));

        date.setText("Date with calender");
        topbar.add(date, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 0, 130, 50));

        getContentPane().add(topbar, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 0, 1080, -1));

        sidepanel.setBackground(new java.awt.Color(0, 153, 153));
        sidepanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        topic1.setBackground(new java.awt.Color(0, 153, 153));
        topic1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bar1.setOpaque(false);

        javax.swing.GroupLayout bar1Layout = new javax.swing.GroupLayout(bar1);
        bar1.setLayout(bar1Layout);
        bar1Layout.setHorizontalGroup(
            bar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        bar1Layout.setVerticalGroup(
            bar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        topic1.add(bar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 10, 60));

        name.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        name.setForeground(new java.awt.Color(255, 255, 255));
        name.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        name.setText(" Home");
        topic1.add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 9, 260, 40));

        pic.setIcon(new javax.swing.ImageIcon(getClass().getResource("/itpshnew/images/icons8_Home_48px.png"))); // NOI18N
        topic1.add(pic, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 50, 40));

        sidepanel.add(topic1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 290, 60));

        topic2.setBackground(new java.awt.Color(0, 153, 153));
        topic2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bar2.setOpaque(false);
        bar2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                bar2topic2MousePressed(evt);
            }
        });

        javax.swing.GroupLayout bar2Layout = new javax.swing.GroupLayout(bar2);
        bar2.setLayout(bar2Layout);
        bar2Layout.setHorizontalGroup(
            bar2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        bar2Layout.setVerticalGroup(
            bar2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        topic2.add(bar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 10, 60));

        name1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        name1.setForeground(new java.awt.Color(255, 255, 255));
        name1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        name1.setText("Sales");
        topic2.add(name1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 9, 260, 40));

        pic1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/itpshnew/images/icons8_Cash_Register_40px_1.png"))); // NOI18N
        topic2.add(pic1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 50, 40));

        sidepanel.add(topic2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, 290, 60));

        topic3.setBackground(new java.awt.Color(0, 153, 153));
        topic3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bar3.setOpaque(false);

        javax.swing.GroupLayout bar3Layout = new javax.swing.GroupLayout(bar3);
        bar3.setLayout(bar3Layout);
        bar3Layout.setHorizontalGroup(
            bar3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        bar3Layout.setVerticalGroup(
            bar3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        topic3.add(bar3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 10, 60));

        name2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        name2.setForeground(new java.awt.Color(255, 255, 255));
        name2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        name2.setText("  Repair");
        topic3.add(name2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 9, 260, 40));

        pic2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/itpshnew/images/icons8_Maintenance_40px.png"))); // NOI18N
        topic3.add(pic2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 50, 40));

        sidepanel.add(topic3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, 290, 60));

        topic4.setBackground(new java.awt.Color(0, 153, 153));
        topic4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bar4.setOpaque(false);

        javax.swing.GroupLayout bar4Layout = new javax.swing.GroupLayout(bar4);
        bar4.setLayout(bar4Layout);
        bar4Layout.setHorizontalGroup(
            bar4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        bar4Layout.setVerticalGroup(
            bar4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        topic4.add(bar4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 10, 60));

        name3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        name3.setForeground(new java.awt.Color(255, 255, 255));
        name3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        name3.setText(" Stock");
        topic4.add(name3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 9, 260, 40));

        pic3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/itpshnew/images/icons8_Warehouse_40px.png"))); // NOI18N
        topic4.add(pic3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 50, 40));

        sidepanel.add(topic4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 310, 290, 60));

        topic5.setBackground(new java.awt.Color(0, 153, 153));
        topic5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                topic5MousePressed(evt);
            }
        });
        topic5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bar5.setOpaque(false);
        bar5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                bar5topic5MousePressed(evt);
            }
        });

        javax.swing.GroupLayout bar5Layout = new javax.swing.GroupLayout(bar5);
        bar5.setLayout(bar5Layout);
        bar5Layout.setHorizontalGroup(
            bar5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        bar5Layout.setVerticalGroup(
            bar5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        topic5.add(bar5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 10, 60));

        name4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        name4.setForeground(new java.awt.Color(255, 255, 255));
        name4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        name4.setText("           Distribution");
        name4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                name4topic5MousePressed(evt);
            }
        });
        topic5.add(name4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 9, 260, 40));

        pic4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/itpshnew/images/icons8_Delivered_40px.png"))); // NOI18N
        pic4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pic4topic5MousePressed(evt);
            }
        });
        topic5.add(pic4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 50, 40));

        sidepanel.add(topic5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 380, 290, 60));

        topic6.setBackground(new java.awt.Color(0, 153, 153));
        topic6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bar6.setOpaque(false);

        javax.swing.GroupLayout bar6Layout = new javax.swing.GroupLayout(bar6);
        bar6.setLayout(bar6Layout);
        bar6Layout.setHorizontalGroup(
            bar6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        bar6Layout.setVerticalGroup(
            bar6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        topic6.add(bar6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 10, 60));

        name5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        name5.setForeground(new java.awt.Color(255, 255, 255));
        name5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        name5.setText("    Finance");
        topic6.add(name5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 9, 260, 40));

        pic5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/itpshnew/images/icons8_Money_Bag_40px.png"))); // NOI18N
        topic6.add(pic5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 50, 40));

        sidepanel.add(topic6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 450, 290, 60));

        topic7.setBackground(new java.awt.Color(0, 153, 153));
        topic7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bar7.setOpaque(false);

        javax.swing.GroupLayout bar7Layout = new javax.swing.GroupLayout(bar7);
        bar7.setLayout(bar7Layout);
        bar7Layout.setHorizontalGroup(
            bar7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        bar7Layout.setVerticalGroup(
            bar7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        topic7.add(bar7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 10, 60));

        name6.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        name6.setForeground(new java.awt.Color(255, 255, 255));
        name6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        name6.setText("HR");
        topic7.add(name6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 9, 230, 40));

        pic6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/itpshnew/images/icons8_User_Group_Man_Man_40px.png"))); // NOI18N
        topic7.add(pic6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 50, 40));

        sidepanel.add(topic7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 510, 290, 60));

        jLabel1.setFont(new java.awt.Font("Lucida Calligraphy", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("City Mobile");
        sidepanel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 270, 60));
        sidepanel.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 650, 270, 20));
        sidepanel.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 270, 10));

        topic8.setBackground(new java.awt.Color(0, 153, 153));
        topic8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bar8.setOpaque(false);

        javax.swing.GroupLayout bar8Layout = new javax.swing.GroupLayout(bar8);
        bar8.setLayout(bar8Layout);
        bar8Layout.setHorizontalGroup(
            bar8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        bar8Layout.setVerticalGroup(
            bar8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        topic8.add(bar8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 10, 60));

        name7.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        name7.setForeground(new java.awt.Color(255, 255, 255));
        name7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        name7.setText("   Web");
        topic8.add(name7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 9, 230, 40));

        pic7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/itpshnew/images/icons8_Web_Design_40px.png"))); // NOI18N
        topic8.add(pic7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 50, 40));

        sidepanel.add(topic8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 570, 290, 60));

        jLabel6.setText("Empid16428685662");
        sidepanel.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 670, 170, 50));

        getContentPane().add(sidepanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 810));

        center.setBackground(new java.awt.Color(199, 238, 238));
        center.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(0, 204, 204));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("  Add Vendor Details");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 50));

        center.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 500, 50));

        jPanel1.setBackground(new java.awt.Color(187, 237, 211));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel8.setBackground(new java.awt.Color(100, 199, 150));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel27.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel27.setText("Vendor Name");
        jPanel8.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 110, 30));

        jTextField19.setText("           ");
        jPanel8.add(jTextField19, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 20, 220, 25));

        jLabel28.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel28.setText("Address");
        jPanel8.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 110, 30));

        jLabel29.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel29.setText("Email ");
        jPanel8.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 110, 30));

        jLabel30.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel30.setText("Phone Number");
        jPanel8.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 150, 30));

        jLabel31.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel31.setText("Shipping Costs");
        jPanel8.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 150, 30));

        jTextField20.setText("           ");
        jPanel8.add(jTextField20, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 70, 220, 25));

        jTextField21.setText("           ");
        jPanel8.add(jTextField21, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 120, 220, 25));

        jTextField22.setText("           ");
        jTextField22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField22ActionPerformed(evt);
            }
        });
        jPanel8.add(jTextField22, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 170, 220, 25));

        jTextField23.setText("           ");
        jPanel8.add(jTextField23, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 220, 220, 25));

        jPanel1.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 460, 270));

        save_btn.setBackground(new java.awt.Color(71, 179, 71));
        save_btn.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        save_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/itpshnew/images/icons8_Save_40px.png"))); // NOI18N
        save_btn.setText("  Save");
        save_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                save_btnActionPerformed(evt);
            }
        });
        jPanel1.add(save_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 300, 170, 45));

        cancel_btn.setBackground(new java.awt.Color(71, 179, 71));
        cancel_btn.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        cancel_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/itpshnew/images/icons8_Cancel_Subscription_30px.png"))); // NOI18N
        cancel_btn.setText("Clear");
        cancel_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancel_btnActionPerformed(evt);
            }
        });
        jPanel1.add(cancel_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 300, 170, 45));

        center.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 500, 360));

        jPanel2.setBackground(new java.awt.Color(187, 237, 211));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel9.setBackground(new java.awt.Color(100, 199, 150));
        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel32.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel32.setText("Name");
        jPanel9.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 110, 30));

        jTextField24.setText("           ");
        jPanel9.add(jTextField24, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 20, 220, 25));

        jLabel33.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel33.setText("Date");
        jPanel9.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 110, 30));

        jLabel34.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel34.setText("Time");
        jPanel9.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 110, 30));

        jLabel35.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel35.setText("Shipping Costs");
        jPanel9.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 150, 30));

        jLabel36.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel36.setText("Item");
        jPanel9.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 150, 30));

        jTextField25.setText("           ");
        jPanel9.add(jTextField25, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 70, 220, 25));

        jTextField26.setText("           ");
        jPanel9.add(jTextField26, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 120, 220, 25));

        jTextField27.setText("           ");
        jTextField27.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField27ActionPerformed(evt);
            }
        });
        jPanel9.add(jTextField27, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 180, 220, 25));

        jTextField28.setText("           ");
        jPanel9.add(jTextField28, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 230, 220, 25));

        jLabel37.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel37.setText("Quantity");
        jPanel9.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, 150, 30));

        jTextField29.setText("           ");
        jPanel9.add(jTextField29, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 280, 220, 25));

        jLabel38.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel38.setText("Type");
        jPanel9.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, 150, 30));

        jRadioButton3.setBackground(new java.awt.Color(100, 199, 150));
        jRadioButton3.setText("Vendor");
        jPanel9.add(jRadioButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 330, -1, -1));

        jRadioButton4.setBackground(new java.awt.Color(100, 199, 150));
        jRadioButton4.setText("Retailer");
        jPanel9.add(jRadioButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 330, -1, -1));

        jLabel39.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel39.setText("Cost");
        jPanel9.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 370, 150, 30));

        jTextField30.setText("           ");
        jPanel9.add(jTextField30, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 370, 220, 25));

        jPanel2.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 460, 430));

        save_btn1.setBackground(new java.awt.Color(71, 179, 71));
        save_btn1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        save_btn1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/itpshnew/images/icons8_Save_40px.png"))); // NOI18N
        save_btn1.setText("  Save");
        save_btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                save_btn1ActionPerformed(evt);
            }
        });
        jPanel2.add(save_btn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 450, 170, 45));

        cancel_btn1.setBackground(new java.awt.Color(71, 179, 71));
        cancel_btn1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        cancel_btn1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/itpshnew/images/icons8_Cancel_Subscription_30px.png"))); // NOI18N
        cancel_btn1.setText("Clear");
        cancel_btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancel_btn1ActionPerformed(evt);
            }
        });
        jPanel2.add(cancel_btn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 450, 170, 45));

        center.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 50, 500, 520));

        jPanel4.setBackground(new java.awt.Color(0, 204, 204));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Register Shipping");
        jPanel4.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 50));

        center.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 0, 500, -1));

        jTable1.setBackground(new java.awt.Color(100, 199, 150));
        jTable1.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jTable1.setForeground(new java.awt.Color(51, 51, 51));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Name", "Date", "Time", "Shipping Cost", "Item", "Quantity", "Type", "Cost"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Float.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.Float.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable1.setGridColor(new java.awt.Color(255, 255, 255));
        jScrollPane1.setViewportView(jTable1);

        center.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 580, 1010, 90));

        jButton7.setBackground(new java.awt.Color(100, 199, 150));
        jButton7.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jButton7.setText("Edit");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        center.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 680, 70, 30));

        jButton8.setBackground(new java.awt.Color(100, 199, 150));
        jButton8.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jButton8.setText("Remove");
        center.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 680, 100, 30));

        jButton9.setBackground(new java.awt.Color(100, 199, 150));
        jButton9.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jButton9.setText("Done");
        center.add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 680, 70, -1));

        getContentPane().add(center, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 56, 1080, 754));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void closeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMouseClicked
        System.exit(0); // cancel button
    }//GEN-LAST:event_closeMouseClicked

    private void minimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizeMouseClicked
        //minimize label
        this.setExtendedState(JFrame.ICONIFIED);
    }//GEN-LAST:event_minimizeMouseClicked

    private void bar2topic2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bar2topic2MousePressed
        /* setColor(topic2);   //set the colour
        bar2.setOpaque(true);  */
    }//GEN-LAST:event_bar2topic2MousePressed

    private void bar5topic5MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bar5topic5MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_bar5topic5MousePressed

    private void name4topic5MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_name4topic5MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_name4topic5MousePressed

    private void pic4topic5MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pic4topic5MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_pic4topic5MousePressed

    private void topic5MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_topic5MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_topic5MousePressed

    private void jTextField22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField22ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField22ActionPerformed

    private void save_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_save_btnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_save_btnActionPerformed

    private void cancel_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancel_btnActionPerformed
        jTextField19.setText("");
        jTextField20.setText("");
        jTextField21.setText("");
        jTextField22.setText("");
        jTextField23.setText("");
    }//GEN-LAST:event_cancel_btnActionPerformed

    private void jTextField27ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField27ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField27ActionPerformed

    private void save_btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_save_btn1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_save_btn1ActionPerformed

    private void cancel_btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancel_btn1ActionPerformed
        jTextField24.setText("");
        jTextField25.setText("");
        jTextField26.setText("");
        jTextField27.setText("");
        jTextField28.setText("");
        jTextField29.setText("");
        jTextField30.setText("");
        jRadioButton3.setSelected(false);
        jRadioButton4.setSelected(false);
    }//GEN-LAST:event_cancel_btn1ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Distribution.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Distribution().setVisible(true);
        });
    }

    public class TimerThread extends Thread
    {
        private JLabel time;
        private boolean running;
        private SimpleDateFormat timeFormat = new SimpleDateFormat("h:mm a");
        
        public TimerThread(JLabel time)
        {
            this.time = time;
            running = true;
        }
        
        public void setRunning(boolean running)
        {
            this.running = running;
        }
        
        public void run()
        {
            while(running)
            {
                SwingUtilities.invokeLater(new Runnable()
                {
                    public void run()
                    {
                        time.setText(timeFormat.format(Calendar.getInstance().getTime()));
                    }
                });
                try
                {
                    sleep(1000);
                }
                catch(InterruptedException e){}
            }
        }
    }
    
    private String getDate()
    {
        Calendar cal = Calendar.getInstance();
        return cal.get(Calendar.DATE)+" "+getMonth()+" "+cal.get(Calendar.YEAR);
    }
    
    private static String getMonth()
    {
        String months[] = {"January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December"};
        return months[Calendar.getInstance().get(Calendar.MONTH)];
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bar1;
    private javax.swing.JPanel bar2;
    private javax.swing.JPanel bar3;
    private javax.swing.JPanel bar4;
    private javax.swing.JPanel bar5;
    private javax.swing.JPanel bar6;
    private javax.swing.JPanel bar7;
    private javax.swing.JPanel bar8;
    private javax.swing.JButton cancel_btn;
    private javax.swing.JButton cancel_btn1;
    private javax.swing.JPanel center;
    private javax.swing.JLabel close;
    private javax.swing.JLabel date;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField19;
    private javax.swing.JTextField jTextField20;
    private javax.swing.JTextField jTextField21;
    private javax.swing.JTextField jTextField22;
    private javax.swing.JTextField jTextField23;
    private javax.swing.JTextField jTextField24;
    private javax.swing.JTextField jTextField25;
    private javax.swing.JTextField jTextField26;
    private javax.swing.JTextField jTextField27;
    private javax.swing.JTextField jTextField28;
    private javax.swing.JTextField jTextField29;
    private javax.swing.JTextField jTextField30;
    private javax.swing.JLabel minimize;
    private javax.swing.JLabel name;
    private javax.swing.JLabel name1;
    private javax.swing.JLabel name2;
    private javax.swing.JLabel name3;
    private javax.swing.JLabel name4;
    private javax.swing.JLabel name5;
    private javax.swing.JLabel name6;
    private javax.swing.JLabel name7;
    private javax.swing.JLabel pic;
    private javax.swing.JLabel pic1;
    private javax.swing.JLabel pic2;
    private javax.swing.JLabel pic3;
    private javax.swing.JLabel pic4;
    private javax.swing.JLabel pic5;
    private javax.swing.JLabel pic6;
    private javax.swing.JLabel pic7;
    private javax.swing.JButton save_btn;
    private javax.swing.JButton save_btn1;
    private javax.swing.JPanel sidepanel;
    private javax.swing.JLabel time;
    private javax.swing.JPanel topbar;
    private javax.swing.JPanel topic1;
    private javax.swing.JPanel topic2;
    private javax.swing.JPanel topic3;
    private javax.swing.JPanel topic4;
    private javax.swing.JPanel topic5;
    private javax.swing.JPanel topic6;
    private javax.swing.JPanel topic7;
    private javax.swing.JPanel topic8;
    // End of variables declaration//GEN-END:variables
}
