/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package itpshnew;

import java.awt.Color;
import java.awt.event.*;
import javax.swing.*;

/**
 *
 * @author isira
 */
public class Main extends javax.swing.JFrame {
    
    private MonthFinancialSystem mfs;
    private TodayFinancialSystem tfs;
    
    private AddVendor av;
    private VendorRecord vr;
    private RetailRecord rr;
    
    private Item i;
    private Stocks s;
    private Reports r;
    
    private TimerThread t;
    /**
     * Creates new form Main
     * @param name
     * @param e 
     */
    
    public Main(String name, MouseEvent e)
    {
        mfs = new MonthFinancialSystem();
        tfs = new TodayFinancialSystem();
        vr = new VendorRecord();
        rr = new RetailRecord();
        r = new Reports();
        i = new Item();
        s = new Stocks();
        av = new AddVendor();
        setEnabledVisible(mfs, false);
        setEnabledVisible(tfs, false);
        setEnabledVisible(vr, false);
        setEnabledVisible(rr, false);
        setEnabledVisible(r, false);
        setEnabledVisible(s, false);
        setEnabledVisible(i, false);
        initComponents();
        t = new TimerThread(time);
        t.start();
        if(name.equals("Finance"))
            topic6MouseClicked(e);
        else if(name.equals("Distribution"))
            topic5MouseClicked(e);
    }
    
    public Main()
    {
        mfs = new MonthFinancialSystem();
        tfs = new TodayFinancialSystem();
        vr = new VendorRecord();
        rr = new RetailRecord();
        r = new Reports();
        i = new Item();
        s = new Stocks();
        av = new AddVendor();
        setEnabledVisible(mfs, false);
        setEnabledVisible(tfs, false);
        setEnabledVisible(vr, false);
        setEnabledVisible(rr, false);
        setEnabledVisible(r, false);
        setEnabledVisible(s, false);
        setEnabledVisible(i, false);
        initComponents();
        t = new TimerThread(time);
        t.start();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sidepanel = new javax.swing.JPanel();
        topic1 = new javax.swing.JPanel();
        bar1 = new javax.swing.JPanel();
        name = new javax.swing.JLabel();
        pic = new javax.swing.JLabel();
        topic2 = new javax.swing.JPanel();
        bar2 = new javax.swing.JPanel();
        pic3 = new javax.swing.JLabel();
        name1 = new javax.swing.JLabel();
        topic3 = new javax.swing.JPanel();
        bar3 = new javax.swing.JPanel();
        name2 = new javax.swing.JLabel();
        pic2 = new javax.swing.JLabel();
        topic4 = new javax.swing.JPanel();
        bar4 = new javax.swing.JPanel();
        name3 = new javax.swing.JLabel();
        pic1 = new javax.swing.JLabel();
        topic5 = new javax.swing.JPanel();
        bar5 = new javax.swing.JPanel();
        name4 = new javax.swing.JLabel();
        pic4 = new javax.swing.JLabel();
        topic6 = new javax.swing.JPanel();
        bar6 = new javax.swing.JPanel();
        name5 = new javax.swing.JLabel();
        pic5 = new javax.swing.JLabel();
        topic7 = new javax.swing.JPanel();
        bar7 = new javax.swing.JPanel();
        name6 = new javax.swing.JLabel();
        pic6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator1 = new javax.swing.JSeparator();
        topic8 = new javax.swing.JPanel();
        bar8 = new javax.swing.JPanel();
        name7 = new javax.swing.JLabel();
        pic7 = new javax.swing.JLabel();
        emp_name = new javax.swing.JLabel();
        emp_id = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        topbar = new javax.swing.JPanel();
        close = new javax.swing.JLabel();
        minimize = new javax.swing.JLabel();
        time = new javax.swing.JLabel();
        date = new javax.swing.JLabel();
        adddetail = new javax.swing.JLabel();
        adddetail1 = new javax.swing.JLabel();
        vendor = new javax.swing.JLabel();
        today = new javax.swing.JLabel();
        retail = new javax.swing.JLabel();
        month = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1366, 768));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(1366, 768));
        setResizable(false);
        setSize(new java.awt.Dimension(1366, 768));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        sidepanel.setBackground(new java.awt.Color(0, 153, 153));
        sidepanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        topic1.setBackground(new java.awt.Color(0, 153, 153));
        topic1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                topic1bar1MousePressed(evt);
            }
        });
        topic1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bar1.setOpaque(false);
        bar1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                bar1MousePressed(evt);
            }
        });

        javax.swing.GroupLayout bar1Layout = new javax.swing.GroupLayout(bar1);
        bar1.setLayout(bar1Layout);
        bar1Layout.setHorizontalGroup(
            bar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        bar1Layout.setVerticalGroup(
            bar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );

        topic1.add(bar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 10, 60));

        name.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        name.setForeground(new java.awt.Color(255, 255, 255));
        name.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        name.setText(" Home");
        name.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                namebar1MousePressed(evt);
            }
        });
        topic1.add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 9, 260, 40));

        pic.setIcon(new javax.swing.ImageIcon(getClass().getResource("/itpshnew/images/icons8_Home_48px.png"))); // NOI18N
        topic1.add(pic, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 50, 40));

        sidepanel.add(topic1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 290, 60));

        topic2.setBackground(new java.awt.Color(0, 153, 153));
        topic2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                topic2MousePressed(evt);
            }
        });
        topic2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bar2.setBackground(new java.awt.Color(255, 255, 255));
        bar2.setOpaque(false);
        bar2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                bar2topic2MousePressed(evt);
            }
        });

        javax.swing.GroupLayout bar2Layout = new javax.swing.GroupLayout(bar2);
        bar2.setLayout(bar2Layout);
        bar2Layout.setHorizontalGroup(
            bar2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        bar2Layout.setVerticalGroup(
            bar2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );

        topic2.add(bar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 10, 60));

        pic3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/itpshnew/images/icons8_Warehouse_40px.png"))); // NOI18N
        pic3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pic3name3MousePressed(evt);
            }
        });
        topic2.add(pic3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 50, 40));

        name1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        name1.setForeground(new java.awt.Color(255, 255, 255));
        name1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        name1.setText("Stock");
        name1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                name1MouseClicked(evt);
            }
        });
        topic2.add(name1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 9, 260, 40));

        sidepanel.add(topic2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, 290, 60));

        topic3.setBackground(new java.awt.Color(0, 153, 153));
        topic3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bar3.setOpaque(false);

        javax.swing.GroupLayout bar3Layout = new javax.swing.GroupLayout(bar3);
        bar3.setLayout(bar3Layout);
        bar3Layout.setHorizontalGroup(
            bar3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        bar3Layout.setVerticalGroup(
            bar3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );

        topic3.add(bar3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 10, 60));

        name2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        name2.setForeground(new java.awt.Color(255, 255, 255));
        name2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        name2.setText("  Repair");
        topic3.add(name2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 9, 260, 40));

        pic2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/itpshnew/images/icons8_Maintenance_40px.png"))); // NOI18N
        topic3.add(pic2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 50, 40));

        sidepanel.add(topic3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, 290, 60));

        topic4.setBackground(new java.awt.Color(0, 153, 153));
        topic4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                topic4name3MousePressed(evt);
            }
        });
        topic4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bar4.setOpaque(false);
        bar4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                bar4name3MousePressed(evt);
            }
        });

        javax.swing.GroupLayout bar4Layout = new javax.swing.GroupLayout(bar4);
        bar4.setLayout(bar4Layout);
        bar4Layout.setHorizontalGroup(
            bar4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        bar4Layout.setVerticalGroup(
            bar4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );

        topic4.add(bar4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 10, 60));

        name3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        name3.setForeground(new java.awt.Color(255, 255, 255));
        name3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        name3.setText("Sales");
        name3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                name3MousePressed(evt);
            }
        });
        topic4.add(name3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 9, 260, 40));

        pic1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/itpshnew/images/icons8_Cash_Register_40px_1.png"))); // NOI18N
        pic1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pic1topic2MousePressed(evt);
            }
        });
        topic4.add(pic1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 50, 40));

        sidepanel.add(topic4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 310, 290, 60));

        topic5.setBackground(new java.awt.Color(0, 153, 153));
        topic5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                topic5MouseClicked(evt);
            }
        });
        topic5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bar5.setOpaque(false);

        javax.swing.GroupLayout bar5Layout = new javax.swing.GroupLayout(bar5);
        bar5.setLayout(bar5Layout);
        bar5Layout.setHorizontalGroup(
            bar5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        bar5Layout.setVerticalGroup(
            bar5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );

        topic5.add(bar5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 10, 60));

        name4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        name4.setForeground(new java.awt.Color(255, 255, 255));
        name4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        name4.setText("           Distribution");
        name4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                name4MouseClicked(evt);
            }
        });
        topic5.add(name4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 9, 260, 40));

        pic4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/itpshnew/images/icons8_Delivered_40px.png"))); // NOI18N
        topic5.add(pic4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 50, 40));

        sidepanel.add(topic5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 380, 290, 60));

        topic6.setBackground(new java.awt.Color(0, 153, 153));
        topic6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                topic6MouseClicked(evt);
            }
        });
        topic6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bar6.setOpaque(false);
        bar6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                bar6topic6MousePressed(evt);
            }
        });

        javax.swing.GroupLayout bar6Layout = new javax.swing.GroupLayout(bar6);
        bar6.setLayout(bar6Layout);
        bar6Layout.setHorizontalGroup(
            bar6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        bar6Layout.setVerticalGroup(
            bar6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );

        topic6.add(bar6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 10, 60));

        name5.setBackground(new java.awt.Color(0, 153, 153));
        name5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        name5.setForeground(new java.awt.Color(255, 255, 255));
        name5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        name5.setText("    Finance");
        name5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                name5MouseClicked(evt);
            }
        });
        topic6.add(name5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 9, 260, 40));

        pic5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/itpshnew/images/icons8_Money_Bag_40px.png"))); // NOI18N
        pic5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pic5topic6MousePressed(evt);
            }
        });
        topic6.add(pic5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 50, 40));

        sidepanel.add(topic6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 450, 290, 60));

        topic7.setBackground(new java.awt.Color(0, 153, 153));
        topic7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bar7.setOpaque(false);

        javax.swing.GroupLayout bar7Layout = new javax.swing.GroupLayout(bar7);
        bar7.setLayout(bar7Layout);
        bar7Layout.setHorizontalGroup(
            bar7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        bar7Layout.setVerticalGroup(
            bar7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );

        topic7.add(bar7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 10, 60));

        name6.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        name6.setForeground(new java.awt.Color(255, 255, 255));
        name6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        name6.setText("HR");
        topic7.add(name6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 9, 230, 40));

        pic6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/itpshnew/images/icons8_User_Group_Man_Man_40px.png"))); // NOI18N
        topic7.add(pic6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 50, 40));

        sidepanel.add(topic7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 510, 290, 60));

        jLabel1.setFont(new java.awt.Font("Lucida Calligraphy", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("City Mobile");
        sidepanel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 270, 60));
        sidepanel.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 650, 270, 20));
        sidepanel.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 270, 10));

        topic8.setBackground(new java.awt.Color(0, 153, 153));
        topic8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bar8.setOpaque(false);

        javax.swing.GroupLayout bar8Layout = new javax.swing.GroupLayout(bar8);
        bar8.setLayout(bar8Layout);
        bar8Layout.setHorizontalGroup(
            bar8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        bar8Layout.setVerticalGroup(
            bar8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );

        topic8.add(bar8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 10, 60));

        name7.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        name7.setForeground(new java.awt.Color(255, 255, 255));
        name7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        name7.setText("   Web");
        topic8.add(name7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 9, 230, 40));

        pic7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/itpshnew/images/icons8_Web_Design_40px.png"))); // NOI18N
        topic8.add(pic7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 50, 40));

        sidepanel.add(topic8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 570, 290, 60));

        emp_name.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        emp_name.setForeground(new java.awt.Color(255, 255, 255));
        emp_name.setText("E.N. Employee Name ");
        sidepanel.add(emp_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 660, 210, 50));

        emp_id.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        emp_id.setForeground(new java.awt.Color(255, 255, 255));
        emp_id.setText("EI1725478963");
        sidepanel.add(emp_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 710, 210, 50));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/itpshnew/images/icons8_Employee_Card_80px.png"))); // NOI18N
        sidepanel.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 660, 80, 100));

        getContentPane().add(sidepanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 810));

        topbar.setBackground(new java.awt.Color(0, 204, 204));
        topbar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        close.setIcon(new javax.swing.ImageIcon(getClass().getResource("/itpshnew/images/icons8_Close_Window_40px.png"))); // NOI18N
        close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeMouseClicked(evt);
            }
        });
        topbar.add(close, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 0, -1, 49));

        minimize.setIcon(new javax.swing.ImageIcon(getClass().getResource("/itpshnew/images/icons8_Minimize_Window_40px.png"))); // NOI18N
        minimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minimizeMouseClicked(evt);
            }
        });
        topbar.add(minimize, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 0, -1, 50));

        time.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        time.setForeground(new java.awt.Color(255, 255, 255));
        time.setText("Time");
        topbar.add(time, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 0, 90, 50));

        date.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        date.setForeground(new java.awt.Color(255, 255, 255));
        date.setText(DateTimeFunctions.getDate());
        topbar.add(date, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 0, 190, 50));

        adddetail.setBackground(new java.awt.Color(0, 204, 204));
        adddetail.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        adddetail.setForeground(new java.awt.Color(255, 255, 255));
        adddetail.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        adddetail.setIcon(new javax.swing.ImageIcon(getClass().getResource("/itpshnew/images/icons8_Combo_Chart_30px.png"))); // NOI18N
        adddetail.setText("  Stock Reports");
        adddetail.setEnabled(false);
        adddetail.setVisible(false);
        adddetail.setOpaque(true);
        adddetail.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                adddetailMouseClicked(evt);
            }
        });
        topbar.add(adddetail, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 0, 190, 50));

        adddetail1.setBackground(new java.awt.Color(0, 204, 204));
        adddetail1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        adddetail1.setForeground(new java.awt.Color(255, 255, 255));
        adddetail1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        adddetail1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/itpshnew/images/icons8_Calculator_24px_4.png"))); // NOI18N
        adddetail1.setEnabled(false);
        adddetail1.setOpaque(true);
        adddetail1.setVisible(false);
        adddetail1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                adddetail1MouseClicked(evt);
            }
        });
        topbar.add(adddetail1, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 0, 50, 50));

        vendor.setBackground(new java.awt.Color(0, 204, 204));
        vendor.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        vendor.setForeground(new java.awt.Color(255, 255, 255));
        vendor.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        vendor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/itpshnew/images/icons8_Warranty_Card_30px_2.png"))); // NOI18N
        vendor.setText("  New Item");
        vendor.setEnabled(false);
        vendor.setOpaque(true);
        vendor.setVisible(false);
        vendor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                vendorMouseClicked(evt);
            }
        });
        topbar.add(vendor, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 180, 50));

        today.setBackground(new java.awt.Color(0, 204, 204));
        today.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        today.setForeground(new java.awt.Color(255, 255, 255));
        today.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        today.setIcon(new javax.swing.ImageIcon(getClass().getResource("/itpshnew/images/icons8_Money_30px_1.png"))); // NOI18N
        today.setText("  Today");
        today.setEnabled(false);
        today.setOpaque(true);
        today.setVisible(false);
        today.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                todayMouseClicked(evt);
            }
        });
        topbar.add(today, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 180, 50));

        retail.setBackground(new java.awt.Color(0, 204, 204));
        retail.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        retail.setForeground(new java.awt.Color(255, 255, 255));
        retail.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        retail.setIcon(new javax.swing.ImageIcon(getClass().getResource("/itpshnew/images/icons8_New_Product_30px_1.png"))); // NOI18N
        retail.setText("  Current Stock");
        retail.setEnabled(false);
        retail.setOpaque(true);
        retail.setVisible(false);
        retail.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                retailMouseClicked(evt);
            }
        });
        topbar.add(retail, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 0, 200, 50));

        month.setBackground(new java.awt.Color(0, 204, 204));
        month.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        month.setForeground(new java.awt.Color(255, 255, 255));
        month.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        month.setIcon(new javax.swing.ImageIcon(getClass().getResource("/itpshnew/images/icons8_Money_Bag_40px.png"))); // NOI18N
        month.setText("  Month");
        month.setEnabled(false);
        month.setOpaque(true);
        month.setVisible(false);
        month.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                monthMouseClicked(evt);
            }
        });
        topbar.add(month, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 0, 200, 50));

        getContentPane().add(topbar, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 0, 1090, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bar1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bar1MousePressed

        home.getInstance().setVisible(true);
        dispose();
    }//GEN-LAST:event_bar1MousePressed

    private void namebar1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_namebar1MousePressed

        bar1MousePressed(evt);
    }//GEN-LAST:event_namebar1MousePressed

    private void topic1bar1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_topic1bar1MousePressed

        bar1MousePressed(evt);
    }//GEN-LAST:event_topic1bar1MousePressed

    private void bar2topic2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bar2topic2MousePressed
        /* setColor(topic2);   //set the colour
        bar2.setOpaque(true);  */

    }//GEN-LAST:event_bar2topic2MousePressed

    private void pic3name3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pic3name3MousePressed

    }//GEN-LAST:event_pic3name3MousePressed

    private void topic2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_topic2MousePressed
        /* setColor(topic2);   //set the colour
        bar2.setOpaque(true);  */

    }//GEN-LAST:event_topic2MousePressed

    private void bar4name3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bar4name3MousePressed

    }//GEN-LAST:event_bar4name3MousePressed

    private void name3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_name3MousePressed

    }//GEN-LAST:event_name3MousePressed

    private void pic1topic2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pic1topic2MousePressed
        /* setColor(topic2);   //set the colour
        bar2.setOpaque(true);  */

    }//GEN-LAST:event_pic1topic2MousePressed

    private void topic4name3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_topic4name3MousePressed

    }//GEN-LAST:event_topic4name3MousePressed

    private void bar6topic6MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bar6topic6MousePressed

    }//GEN-LAST:event_bar6topic6MousePressed

    private void pic5topic6MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pic5topic6MousePressed

    }//GEN-LAST:event_pic5topic6MousePressed

    private void closeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMouseClicked
        t.setRunning(false);
        dispose();
    }//GEN-LAST:event_closeMouseClicked

    private void minimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizeMouseClicked
        setExtendedState(JFrame.ICONIFIED);
    }//GEN-LAST:event_minimizeMouseClicked

    private void vendorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_vendorMouseClicked
        i.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        add(i, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 50, 1090, 760));
        if(i.getLoaded() == false)
            i.pubInit();
        setEnabledVisible(s, false);
        setEnabledVisible(r, false);
        setEnabledVisible(i, true);
        setLabelColor(vendor);
        resetLabelColor(retail);
        resetLabelColor(adddetail);
    }//GEN-LAST:event_vendorMouseClicked

    private void retailMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_retailMouseClicked
        s.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        add(s, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 50, 1090, 760));
        if(s.getLoaded() == false)
            s.pubInit();
        setEnabledVisible(r, false);
        setEnabledVisible(i, false);
        setEnabledVisible(s, true);
        setLabelColor(retail);
        resetLabelColor(vendor);
        resetLabelColor(adddetail);
    }//GEN-LAST:event_retailMouseClicked

    private void adddetailMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_adddetailMouseClicked
        r.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        add(r, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 50, 1090, 760));
        if(r.getLoaded() == false)
            r.pubInit();
        setEnabledVisible(i, false);
        setEnabledVisible(s, false);
        setEnabledVisible(r, true);
        setLabelColor(adddetail);
        resetLabelColor(vendor);
        resetLabelColor(retail);
    }//GEN-LAST:event_adddetailMouseClicked

    private void adddetail1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_adddetail1MouseClicked
        setLabelColor(adddetail1);// TODO add your handling code here:
        adddetail1.setVisible(true);

    }//GEN-LAST:event_adddetail1MouseClicked

    private void name5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_name5MouseClicked
        if(!tfs.isVisible() && !mfs.isVisible())
        {
            resetAll();
            tfs.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
            add(tfs, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 50, 1200, 768));
            if(tfs.getLoaded() == false)
                tfs.pubInit();
            setEnabledVisible(tfs, true);
            setLabelColor(name5);
            setEnabledVisible(today, true);
            setEnabledVisible(month, true);
            setPanelColor(topic6);
            setLabelColor(today);
        }
    }//GEN-LAST:event_name5MouseClicked

    private void todayMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_todayMouseClicked
        tfs.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        add(tfs, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 50, 1200, 768));
        if(tfs.getLoaded() == false)
            tfs.pubInit();
        setEnabledVisible(mfs, false);
        setEnabledVisible(tfs, true);
        setLabelColor(today);
        resetLabelColor(month);
    }//GEN-LAST:event_todayMouseClicked

    private void monthMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_monthMouseClicked
        mfs.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        add(mfs, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 50, 1200, 768));
        if(mfs.getLoaded() == false)
            mfs.pubInit();
        setEnabledVisible(tfs, false);
        setEnabledVisible(mfs, true);
        setLabelColor(month);
        resetLabelColor(today);
    }//GEN-LAST:event_monthMouseClicked

    private void topic6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_topic6MouseClicked
        name5MouseClicked(evt);
    }//GEN-LAST:event_topic6MouseClicked

    private void name1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_name1MouseClicked
        if(!i.isVisible() && !r.isVisible() && !s.isVisible())
        {
            resetAll();
            i.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
            add(i, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 50, 1090, 760));
            if(i.getLoaded() == false)
                i.pubInit();
            setEnabledVisible(i, true);
            setLabelColor(name1);
            setEnabledVisible(retail, true);
            setEnabledVisible(vendor, true);
            setEnabledVisible(adddetail, true);
            setEnabledVisible(adddetail1, true);
            setPanelColor(topic2);
            setLabelColor(vendor);
        }
    }//GEN-LAST:event_name1MouseClicked

    private void name4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_name4MouseClicked
        if(!vr.isVisible() && !rr.isVisible())
        {
            resetAll();
            vr.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
            add(vr, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 50, 1200, 768));
            if(vr.getLoaded() == false)
                vr.pubInit();
            setEnabledVisible(vr, true);
            setPanelColor(topic5);
        }
    }//GEN-LAST:event_name4MouseClicked

    private void topic5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_topic5MouseClicked
        name4MouseClicked(evt);
    }//GEN-LAST:event_topic5MouseClicked

    private void setLabelColor(JLabel label) //set the colour after  click
    {
        label.setBackground(new Color (0,153,153));
    }
    
    private void resetLabelColor(JLabel label) //set the colour after  click
    {
        label.setBackground(new Color (0,204,204));
    }
    
    private void resetPanelColor(JPanel panel)
    {
        panel.setBackground(new Color (0,153,153));
    }
    
    private void setPanelColor(JPanel panel)
    {
        panel.setBackground(new Color (0,204,204));
    }
    
    private void resetComp(JComponent c)
    {
        if(c.isEnabled() && c.isVisible())
        {
            setEnabledVisible(c, false);
        }
    }
    
    private void setEnabledVisible(JComponent c, boolean state)
    {
        c.setEnabled(state);
        c.setVisible(state);
    }
    
    private void resetAll()
    {
        Color c = new Color(0, 204, 204);
        if(topic2.getBackground().equals(c))
            resetPanelColor(topic2);
        if(topic3.getBackground().equals(c))
            resetPanelColor(topic3);
        if(topic4.getBackground().equals(c))
            resetPanelColor(topic4);
        if(topic5.getBackground().equals(c))
            resetPanelColor(topic5);
        if(topic6.getBackground().equals(c))
            resetPanelColor(topic6);
        resetComp(month);
        resetComp(today);
        resetComp(vendor);
        resetComp(retail);
        resetComp(tfs);
        resetComp(mfs);
        resetComp(rr);
        resetComp(vr);
        resetComp(r);
        resetComp(i);
        resetComp(s);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel adddetail;
    private javax.swing.JLabel adddetail1;
    private javax.swing.JPanel bar1;
    private javax.swing.JPanel bar2;
    private javax.swing.JPanel bar3;
    private javax.swing.JPanel bar4;
    private javax.swing.JPanel bar5;
    private javax.swing.JPanel bar6;
    private javax.swing.JPanel bar7;
    private javax.swing.JPanel bar8;
    private javax.swing.JLabel close;
    private javax.swing.JLabel date;
    private javax.swing.JLabel emp_id;
    private javax.swing.JLabel emp_name;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel minimize;
    private javax.swing.JLabel month;
    private javax.swing.JLabel name;
    private javax.swing.JLabel name1;
    private javax.swing.JLabel name2;
    private javax.swing.JLabel name3;
    private javax.swing.JLabel name4;
    private javax.swing.JLabel name5;
    private javax.swing.JLabel name6;
    private javax.swing.JLabel name7;
    private javax.swing.JLabel pic;
    private javax.swing.JLabel pic1;
    private javax.swing.JLabel pic2;
    private javax.swing.JLabel pic3;
    private javax.swing.JLabel pic4;
    private javax.swing.JLabel pic5;
    private javax.swing.JLabel pic6;
    private javax.swing.JLabel pic7;
    private javax.swing.JLabel retail;
    private javax.swing.JPanel sidepanel;
    private javax.swing.JLabel time;
    private javax.swing.JLabel today;
    private javax.swing.JPanel topbar;
    private javax.swing.JPanel topic1;
    private javax.swing.JPanel topic2;
    private javax.swing.JPanel topic3;
    private javax.swing.JPanel topic4;
    private javax.swing.JPanel topic5;
    private javax.swing.JPanel topic6;
    private javax.swing.JPanel topic7;
    private javax.swing.JPanel topic8;
    private javax.swing.JLabel vendor;
    // End of variables declaration//GEN-END:variables
}
