/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package itpshnew;

import com.mysql.jdbc.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author isira
 */
public class Stocks extends StockControl {

    /**
     * Creates new form Stock
     */
    public Stocks() {
        initComponents();
    }

    public void pubInit()
    {
        initComponents();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Stock = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        txtmdl1 = new javax.swing.JTextField();
        txtqty2 = new javax.swing.JTextField();
        txtnro = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jLabel55 = new javax.swing.JLabel();
        txtpro = new javax.swing.JTextField();
        jButton24 = new javax.swing.JButton();
        jButton25 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jPanel10 = new javax.swing.JPanel();
        jLabel48 = new javax.swing.JLabel();
        txtsearch2 = new javax.swing.JTextField();
        jLabel49 = new javax.swing.JLabel();
        jLabel50 = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        jLabel57 = new javax.swing.JLabel();
        txtsearch3 = new javax.swing.JTextField();
        searchme = new javax.swing.JLabel();
        jLabel51 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        txtvendor = new javax.swing.JTextField();
        txtbudget = new javax.swing.JTextField();
        txtqty1 = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        txtup2 = new javax.swing.JTextField();
        txtcb4 = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        txtmc = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        txtbrand2 = new javax.swing.JTextField();
        jButton14 = new javax.swing.JButton();
        jLabel56 = new javax.swing.JLabel();
        jButton16 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();

        Stock.setBackground(new java.awt.Color(202, 254, 227));
        Stock.setAutoscrolls(true);
        Stock.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel8.setBackground(new java.awt.Color(100, 199, 150));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel20.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jLabel20.setText("Model Code");
        jPanel8.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 150, 30));

        jLabel21.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jLabel21.setText("Quantity in Hand");
        jPanel8.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 160, -1));

        txtmdl1.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtmdl1.setBorder(null);
        jPanel8.add(txtmdl1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 10, 260, 25));

        txtqty2.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtqty2.setBorder(null);
        txtqty2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtqty2ActionPerformed(evt);
            }
        });
        jPanel8.add(txtqty2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 50, 260, 25));

        txtnro.setBorder(null);
        txtnro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnroActionPerformed(evt);
            }
        });
        jPanel8.add(txtnro, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 130, 260, 25));

        jLabel22.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jLabel22.setText("Current Re-Order Level");
        jPanel8.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 220, -1));

        jLabel55.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jLabel55.setText("New Re-Order Level");
        jPanel8.add(jLabel55, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, -1, -1));

        txtpro.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtpro.setBorder(null);
        txtpro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtproActionPerformed(evt);
            }
        });
        jPanel8.add(txtpro, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 90, 260, 25));

        jButton24.setBackground(new java.awt.Color(100, 199, 150));
        jButton24.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jButton24.setText("Default Limit");
        jButton24.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jButton24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton24ActionPerformed(evt);
            }
        });
        jPanel8.add(jButton24, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 170, 120, 30));

        jButton25.setBackground(new java.awt.Color(100, 199, 150));
        jButton25.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jButton25.setText("Set Limit");
        jButton25.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jButton25.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton25ActionPerformed(evt);
            }
        });
        jPanel8.add(jButton25, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 170, 130, 30));

        Stock.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 410, 520, 210));

        jButton12.setBackground(new java.awt.Color(48, 214, 48));
        jButton12.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/itpshnew/images/icons8_Reset_40px.png"))); // NOI18N
        jButton12.setText("Refresh");
        jButton12.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });
        Stock.add(jButton12, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 640, 240, 60));

        jPanel10.setBackground(new java.awt.Color(100, 199, 150));
        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel48.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel48.setText("Model Code");
        jPanel10.add(jLabel48, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 150, -1));

        txtsearch2.setBorder(null);
        txtsearch2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtsearch2ActionPerformed(evt);
            }
        });
        jPanel10.add(txtsearch2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 10, 740, 30));

        jLabel49.setIcon(new javax.swing.ImageIcon(getClass().getResource("/itpshnew/images/icons8_Google_Web_Search_40px.png"))); // NOI18N
        jLabel49.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel49MouseClicked(evt);
            }
        });
        jPanel10.add(jLabel49, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 0, 40, 50));

        Stock.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 1040, 50));

        jLabel50.setFont(new java.awt.Font("Segoe UI Black", 2, 29)); // NOI18N
        jLabel50.setForeground(new java.awt.Color(0, 153, 0));
        jLabel50.setText("Set Re-Order Level");
        Stock.add(jLabel50, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 330, 340, 120));

        jPanel12.setBackground(new java.awt.Color(100, 199, 150));
        jPanel12.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel57.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel57.setText("Reorder Brand");
        jPanel12.add(jLabel57, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 180, -1));

        txtsearch3.setBorder(null);
        txtsearch3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtsearch3ActionPerformed(evt);
            }
        });
        jPanel12.add(txtsearch3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 10, 740, 30));

        searchme.setIcon(new javax.swing.ImageIcon(getClass().getResource("/itpshnew/images/icons8_Google_Web_Search_40px.png"))); // NOI18N
        searchme.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                searchmeMouseClicked(evt);
            }
        });
        jPanel12.add(searchme, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 0, 40, 50));

        Stock.add(jPanel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 1040, 50));

        jLabel51.setFont(new java.awt.Font("Segoe UI Black", 2, 36)); // NOI18N
        jLabel51.setForeground(new java.awt.Color(0, 153, 0));
        jLabel51.setText("Search");
        Stock.add(jLabel51, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jPanel5.setBackground(new java.awt.Color(100, 199, 150));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel14.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jLabel14.setText("Vendor ID");
        jPanel5.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 45, 140, 30));

        jLabel15.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jLabel15.setText("Model Code");
        jPanel5.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 150, 60));

        jLabel16.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jLabel16.setText("Quantity");
        jPanel5.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, -1, -1));

        txtvendor.setBorder(null);
        jPanel5.add(txtvendor, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 50, 310, 25));

        txtbudget.setBorder(null);
        jPanel5.add(txtbudget, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 170, 310, 25));

        txtqty1.setBorder(null);
        txtqty1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtqty1ActionPerformed(evt);
            }
        });
        jPanel5.add(txtqty1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 210, 140, 25));

        jLabel17.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jLabel17.setText("Unit Price");
        jPanel5.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, -1, -1));

        jButton8.setBackground(new java.awt.Color(100, 199, 150));
        jButton8.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jButton8.setText("Re-Order Now");
        jButton8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 210, 150, 30));

        jButton9.setBackground(new java.awt.Color(100, 199, 150));
        jButton9.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jButton9.setText("Clear");
        jButton9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 250, 150, 30));

        txtup2.setBorder(null);
        txtup2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtup2ActionPerformed(evt);
            }
        });
        jPanel5.add(txtup2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 250, 140, 25));

        txtcb4.setBorder(null);
        txtcb4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcb4ActionPerformed(evt);
            }
        });
        jPanel5.add(txtcb4, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 10, 310, 25));

        jLabel19.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jLabel19.setText("Brand");
        jPanel5.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 60, 60));

        jLabel23.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jLabel23.setText("Re-Order ID");
        jPanel5.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        txtmc.setBorder(null);
        txtmc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtmcActionPerformed(evt);
            }
        });
        jPanel5.add(txtmc, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 130, 310, 25));

        jLabel29.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jLabel29.setText("Company Budget");
        jPanel5.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 155, 170, 50));

        txtbrand2.setBorder(null);
        txtbrand2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtbrand2ActionPerformed(evt);
            }
        });
        jPanel5.add(txtbrand2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 90, 310, 25));

        Stock.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 410, 500, 290));

        jButton14.setBackground(new java.awt.Color(48, 214, 48));
        jButton14.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/itpshnew/images/icons8_Eye_48px.png"))); // NOI18N
        jButton14.setText("View Re-Orders");
        jButton14.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });
        Stock.add(jButton14, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 640, 260, 60));

        jLabel56.setFont(new java.awt.Font("Segoe UI Black", 2, 29)); // NOI18N
        jLabel56.setForeground(new java.awt.Color(0, 153, 0));
        jLabel56.setText("Re-Order");
        Stock.add(jLabel56, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, -1, 100));

        jButton16.setBackground(new java.awt.Color(100, 199, 150));
        jButton16.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jButton16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/itpshnew/images/icons8_Speedometer_48px.png"))); // NOI18N
        jButton16.setText("Suggested Re-Orders");
        jButton16.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton16ActionPerformed(evt);
            }
        });
        Stock.add(jButton16, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 10, 230, 50));

        jTable2.setBackground(new java.awt.Color(204, 255, 204));
        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable2.setDragEnabled(true);
        jTable2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable2MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable2);

        Stock.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 1040, 240));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1090, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(Stock, javax.swing.GroupLayout.PREFERRED_SIZE, 1090, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 760, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(Stock, javax.swing.GroupLayout.PREFERRED_SIZE, 760, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtqty2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtqty2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtqty2ActionPerformed

    private void txtnroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnroActionPerformed

    private void txtproActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtproActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtproActionPerformed

    private void jButton24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton24ActionPerformed
        try
        {
            String model = txtmdl1.getText();
            String t = "Update availablestock SET reOrderLevel = 10 WHERE modelCode = '"+ model +"'";
            pst = (PreparedStatement) conn.prepareStatement(t);
            pst.execute();
        }
        catch (SQLException ex)
        {
            Logger.getLogger(StockControl.class.getName()).log(Level.SEVERE, null, ex);
        }
        tableLoad(jTable2, "select * from availablestock");
        txtpro.setText("10");
        txtnro.setText("");
        String model = txtmdl1.getText();
        JOptionPane.showMessageDialog(null, " ReOrder Level of "+ model +" set to 10");
    }//GEN-LAST:event_jButton24ActionPerformed

    private void jButton25ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton25ActionPerformed
        String nro = txtnro.getText();
        if(!nro.equals(""))
        {
            int x = JOptionPane.showConfirmDialog(null, "Are you sure you want to change the ReOrder Level?");
            if (x == 0){
                try {
                    String model = txtmdl1.getText();
                    //String nro = txtnro.getText();
                    String t = "Update availablestock SET reOrderLevel = '"+ nro +"' WHERE modelCode = '"+ model +"'";
                    pst = (PreparedStatement) conn.prepareStatement(t);
                    pst.execute();
                } catch (SQLException ex) {
                    Logger.getLogger(StockControl.class.getName()).log(Level.SEVERE, null, ex);
                }
                tableLoad(jTable2, "select * from availablestock");

                //String nro = txtnro.getText();
                String model = txtmdl1.getText();
                txtpro.setText(nro);
                JOptionPane.showMessageDialog(null, " ReOrder Level of "+ model +" set to "+nro);
                txtnro.setText("");
            }
        }
    }//GEN-LAST:event_jButton25ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        tableLoad(jTable2, "select * from availablestock");
        txtqty1.setText("");
        txtbrand2.setText("");
        txtsearch3.setText("");
        txtnro.setText("");
        txtup2.setText("");
        txtvendor.setText("");
        txtbudget.setText("");
        txtsearch2.setText("");
        txtmc.setText("");
        jPanel10.setVisible(true);
        jTable2.setEnabled(true);
        //jLabel49.setVisible(true);
    }//GEN-LAST:event_jButton12ActionPerformed

    private void txtsearch2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtsearch2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtsearch2ActionPerformed

    private void jLabel49MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel49MouseClicked
        String key = txtsearch2.getText();
        try {
            String z1 = "SELECT * FROM availablestock where modelCode LIKE '%"+ key +"%'";
            pst = (PreparedStatement) conn.prepareStatement(z1);
            rs = pst.executeQuery();
            jTable2.setModel(DbUtils.resultSetToTableModel(rs));
        } catch (SQLException ex) {
            Logger.getLogger(StockControl.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jLabel49MouseClicked

    private void txtsearch3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtsearch3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtsearch3ActionPerformed

    private void searchmeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchmeMouseClicked
        String key = txtsearch3.getText();
        try {
            String z1 = "SELECT * FROM reorder where brand LIKE '%"+ key +"%'";
            pst = (PreparedStatement) conn.prepareStatement(z1);
            rs = pst.executeQuery();
            jTable2.setModel(DbUtils.resultSetToTableModel(rs));
        } catch (SQLException ex) {
            Logger.getLogger(StockControl.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_searchmeMouseClicked

    private void txtqty1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtqty1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtqty1ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        boolean goal = false;
        //SetReorderID();

        //JOptionPane.showMessageDialog(null,"Shipping ID cannot be Empty" + rID);
        String Budget = txtbudget.getText();
        String Vendor = txtvendor.getText();
        if (Vendor.equals("") && goal == false){
            JOptionPane.showMessageDialog(null,"Vendor ID cannot be Empty");
            goal = true;
        }

        String Brand = txtbrand2.getText();
        if (Brand.equals("") && goal == false){
            JOptionPane.showMessageDialog(null,"Brand cannot be Empty");
            goal = true;
        }
        if(!Brand.matches("[a-zA-Z]+") && goal == false){
            JOptionPane.showMessageDialog(null,"Brand can only consist of letters");
            goal = true;
        }
        boolean geo = false;
        String Model = txtmc.getText();
        if (Model.equals("") && goal == false){
            JOptionPane.showMessageDialog(null,"Model Code cannot be Empty");
            goal = true;

        }
        int count = 0;
        if (!Model.equals("") && goal == false)
        {
            try
            {
                String SQL = "SELECT * FROM item";
                ResultSet rs = pst.executeQuery(SQL);
                while (rs.next()) {
                    String mc = rs.getString("modelCode");
                    if (Model.equals(mc))
                        count++;
                }
                if(count == 0)
                {
                    int x = JOptionPane.showConfirmDialog(null, "This is a New Product, Do you still wish to ReOrder?");
                    if (x == 0){
                        geo = false;
                    }
                }
                else
                    geo = false;
            } catch (SQLException ex) {
                Logger.getLogger(StockControl.class.getName()).log(Level.SEVERE, null, ex);
            }
        }

        String CB = txtbudget.getText();
        if (CB.equals("") && goal == false){
            JOptionPane.showMessageDialog(null,"Company Budget cannot be Empty");
            goal = true;
        }
        String qty = txtqty1.getText();
        if (qty.equals("") && goal == false){
            JOptionPane.showMessageDialog(null,"Quantity cannot be Empty");
            goal = true;
        }
        String Price = txtup2.getText();
        if (Price.equals("") && goal == false){
            JOptionPane.showMessageDialog(null,"Price cannot be Empty");
            goal = true;
        }

        String reorder = txtcb4.getText();
        if (goal == false && geo == false)
        {
            try
            {
                SimpleDateFormat timeFormat = new SimpleDateFormat("h:mm a");
                double total = Double.parseDouble(Price) * Double.parseDouble(qty);
                double current = Double.parseDouble(Budget);
                if (total < current)
                {
                    String b = "INSERT INTO reorder(reOrderID,vendorID,brand,modelCode,qty,totalCost,RequestDate,RequestTime) "
                    + " values ('"+ reorder +"','"+ Vendor +"','"+ Brand +"','"+ Model +"','"+ qty +"','"+ total +"','"+ DateTimeFunctions.getDate() +"','"+ timeFormat.format(Calendar.getInstance().getTime()) +"')";
                    pst = (PreparedStatement) conn.prepareStatement(b);
                    pst.execute();
                    SetReorderID();
                }
                else
                {
                    JOptionPane.showMessageDialog(null,"Company cannot afford Rs. "+total+"/-", "Cannot place Re-Order",
                        JOptionPane.ERROR_MESSAGE);
                }
            }
            catch(SQLException b)
            {
                JOptionPane.showMessageDialog(null, "Unable to retrieve values.", "Error", JOptionPane.ERROR_MESSAGE);
            }
            tableLoad(jTable2, "select * from reorder");
        }
    }//GEN-LAST:event_jButton8ActionPerformed

    public void SetReorderID()
   {
        try {
            String sql = "select reOrderID from reorder ORDER BY reOrderID DESC LIMIT 1";
            pst = (PreparedStatement) conn.prepareStatement(sql);
            rs = pst.executeQuery();
            if(rs.next())
            {
                String id = rs.getString("reOrderID");
                int len = id.length(); //get length of string
                String letters = id.substring(0,2);
                String numbers = id.substring(2,len);
                int inc = Integer.parseInt(numbers);
                inc = inc + 1;
                numbers = Integer.toString(inc);
                txtcb4.setText(letters+numbers);
            }
            else
            {
                 txtcb4.setText("RE10000001");   
            }
                
                
            
            
            
        } catch (SQLException ex) {
            Logger.getLogger(StockControl.class.getName()).log(Level.SEVERE, null, ex);
        }
       JTable jTable2 = new JTable() {
        private static final long serialVersionUID = 1L;

        @Override
        public boolean isCellEditable(int row, int column) {   //disable jtable editing             
                return false;               
        };
    };
   }
    
    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed

        txtbudget.setText("");
        txtvendor.setText("");
        txtmc.setText("");
        txtqty1.setText("");
        txtup2.setText("");
        txtbrand2.setText("");
    }//GEN-LAST:event_jButton9ActionPerformed

    private void txtup2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtup2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtup2ActionPerformed

    private void txtcb4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcb4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcb4ActionPerformed

    private void txtmcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtmcActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtmcActionPerformed

    private void txtbrand2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtbrand2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtbrand2ActionPerformed

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
        tableLoad(jTable2, "select * from reorder");
        jPanel12.setVisible(true);
        jPanel10.setVisible(false);
        jTable2.setEnabled(false);
        //jLabel49.setVisible(false);
    }//GEN-LAST:event_jButton14ActionPerformed

    private void jButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton16ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton16ActionPerformed

    private void jTable2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable2MouseClicked
        try{
            int r = jTable2.getSelectedRow();
            String mc = jTable2.getValueAt(r,0).toString();
            String qty = jTable2.getValueAt(r,1).toString();
            String level = jTable2.getValueAt(r,2).toString();

            txtmdl1.setText(mc);
            txtqty2.setText(qty);
            txtpro.setText(level);
        }
        catch(Exception e)
        {}
    }//GEN-LAST:event_jTable2MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Stock;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton24;
    private javax.swing.JButton jButton25;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable2;
    private javax.swing.JLabel searchme;
    private javax.swing.JTextField txtbrand2;
    private javax.swing.JTextField txtbudget;
    private javax.swing.JTextField txtcb4;
    private javax.swing.JTextField txtmc;
    private javax.swing.JTextField txtmdl1;
    private javax.swing.JTextField txtnro;
    private javax.swing.JTextField txtpro;
    private javax.swing.JTextField txtqty1;
    private javax.swing.JTextField txtqty2;
    private javax.swing.JTextField txtsearch2;
    private javax.swing.JTextField txtsearch3;
    private javax.swing.JTextField txtup2;
    private javax.swing.JTextField txtvendor;
    // End of variables declaration//GEN-END:variables
}
