/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package itpshnew.distribution;


import java.sql.*;
import javax.swing.*;
import net.proteanit.sql.DbUtils;
/**
 *
 * @author Bhanu
 */
public class AddVendor extends Distribution {

    /**
     * Creates new form AddVendor
     */
    public AddVendor() {
        super();
    }

    @Override
    public void pubInit()
    {
        initComponents();
        loaded = true;
        tableload(vendoradd_table,"select * FROM vendor");
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addvendor = new javax.swing.JPanel();
        print = new javax.swing.JButton();
        jPanel9 = new javax.swing.JPanel();
        jLabel51 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jTextField40 = new javax.swing.JTextField();
        jTextField50 = new javax.swing.JTextField();
        jTextField29 = new javax.swing.JTextField();
        jTextField30 = new javax.swing.JTextField();
        jTextField31 = new javax.swing.JTextField();
        jTextField32 = new javax.swing.JTextField();
        save_btn = new javax.swing.JButton();
        clear_btn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        vendoradd_table = new javax.swing.JTable();
        jPanel10 = new javax.swing.JPanel();
        jLabel44 = new javax.swing.JLabel();
        jTextField33 = new javax.swing.JTextField();
        jLabel45 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        jTextField34 = new javax.swing.JTextField();
        jTextField35 = new javax.swing.JTextField();
        jTextField36 = new javax.swing.JTextField();
        jTextField37 = new javax.swing.JTextField();
        search = new javax.swing.JButton();
        reset_btn = new javax.swing.JButton();
        jLabel49 = new javax.swing.JLabel();
        jTextField38 = new javax.swing.JTextField();
        edit_btn = new javax.swing.JButton();
        clear_btn1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        addvendor.setBackground(new java.awt.Color(202, 254, 227));
        addvendor.setToolTipText("");
        addvendor.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        print.setBackground(new java.awt.Color(48, 214, 48));
        print.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        print.setIcon(new javax.swing.ImageIcon(getClass().getResource("/itpshnew/images/icons8_Print_40px.png"))); // NOI18N
        print.setText("  Print");
        print.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printActionPerformed(evt);
            }
        });
        addvendor.add(print, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 660, 200, 50));

        jPanel9.setBackground(new java.awt.Color(100, 199, 150));
        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel51.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel51.setText("Vendor ID");
        jPanel9.add(jLabel51, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 110, 30));

        jLabel39.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel39.setText("Vendor Name");
        jPanel9.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 110, 30));

        jLabel40.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel40.setText("Address");
        jPanel9.add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 110, 30));

        jLabel41.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel41.setText("Email ");
        jPanel9.add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 110, 30));

        jLabel42.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel42.setText("Phone Number");
        jPanel9.add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 150, 30));

        jLabel43.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel43.setText("Shipping Costs");
        jPanel9.add(jLabel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 150, 30));
        jPanel9.add(jTextField40, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 20, 220, 25));

        jTextField50.setText("    ");
        jPanel9.add(jTextField50, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 60, 220, 25));
        jPanel9.add(jTextField29, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 110, 220, 25));
        jPanel9.add(jTextField30, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 160, 220, 25));

        jTextField31.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField31ActionPerformed(evt);
            }
        });
        jPanel9.add(jTextField31, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 210, 220, 25));
        jPanel9.add(jTextField32, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 260, 220, 25));

        save_btn.setBackground(new java.awt.Color(31, 233, 133));
        save_btn.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        save_btn.setText("Save");
        save_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                save_btnActionPerformed(evt);
            }
        });
        jPanel9.add(save_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 320, 110, 35));

        clear_btn.setBackground(new java.awt.Color(31, 233, 133));
        clear_btn.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        clear_btn.setText("Clear");
        clear_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clear_btnActionPerformed(evt);
            }
        });
        jPanel9.add(clear_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 320, 110, 35));

        addvendor.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 460, 370));

        vendoradd_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Vendor ID", "Vendor Name", "Address", "Email", "Phone", "Shipping Cost"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        vendoradd_table.setGridColor(new java.awt.Color(100, 199, 150));
        jScrollPane1.setViewportView(vendoradd_table);

        addvendor.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 460, 1040, 180));

        jPanel10.setBackground(new java.awt.Color(100, 199, 150));
        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel44.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel44.setText("Vendor Name");
        jPanel10.add(jLabel44, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 110, 30));

        jTextField33.setEditable(false);
        jPanel10.add(jTextField33, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 70, 220, 25));

        jLabel45.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel45.setText("Address");
        jPanel10.add(jLabel45, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 110, 30));

        jLabel46.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel46.setText("Email ");
        jPanel10.add(jLabel46, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, 110, 30));

        jLabel47.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel47.setText("Phone Number");
        jPanel10.add(jLabel47, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, 150, 30));

        jLabel48.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel48.setText("Shipping Costs");
        jPanel10.add(jLabel48, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, 150, 30));

        jTextField34.setEditable(false);
        jPanel10.add(jTextField34, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 120, 220, 25));

        jTextField35.setEditable(false);
        jPanel10.add(jTextField35, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 170, 220, 25));

        jTextField36.setEditable(false);
        jTextField36.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField36ActionPerformed(evt);
            }
        });
        jPanel10.add(jTextField36, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 220, 220, 25));

        jTextField37.setEditable(false);
        jPanel10.add(jTextField37, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 280, 220, 25));

        search.setBackground(new java.awt.Color(31, 233, 133));
        search.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        search.setText("Search");
        search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchActionPerformed(evt);
            }
        });
        jPanel10.add(search, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 20, 110, 35));

        reset_btn.setBackground(new java.awt.Color(31, 233, 133));
        reset_btn.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        reset_btn.setText("Reset");
        reset_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reset_btnActionPerformed(evt);
            }
        });
        jPanel10.add(reset_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 320, 110, 35));

        jLabel49.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel49.setText("Search ID");
        jPanel10.add(jLabel49, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 90, 40));

        jTextField38.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField38ActionPerformed(evt);
            }
        });
        jPanel10.add(jTextField38, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 20, 220, 30));

        edit_btn.setBackground(new java.awt.Color(31, 233, 133));
        edit_btn.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        edit_btn.setText("Save");
        edit_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edit_btnActionPerformed(evt);
            }
        });
        jPanel10.add(edit_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 320, 110, 35));

        clear_btn1.setBackground(new java.awt.Color(31, 233, 133));
        clear_btn1.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        clear_btn1.setText("Edit");
        clear_btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clear_btn1ActionPerformed(evt);
            }
        });
        jPanel10.add(clear_btn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 320, 110, 35));

        addvendor.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 70, 470, 370));

        jLabel2.setFont(new java.awt.Font("Segoe UI Black", 2, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 153, 0));
        jLabel2.setText("Add Vendor");
        addvendor.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 4, 220, 60));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(addvendor, javax.swing.GroupLayout.PREFERRED_SIZE, 1090, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(addvendor, javax.swing.GroupLayout.PREFERRED_SIZE, 760, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void printActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_printActionPerformed

    private void jTextField31ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField31ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField31ActionPerformed

    private void save_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_save_btnActionPerformed

        try
        {
            String VID = jTextField40.getText();
            String vName = jTextField50.getText();
            String address = jTextField29.getText();
            String email;
            if(jTextField30.getText().matches("^[A-Za-z]{1,}+@+[A-Za-z]{1,}+\\.+com$"))
            email = jTextField30.getText();
            else
            {
                JOptionPane.showMessageDialog(this, "Enter a valid email");
                return;
            }
            String phone = jTextField31.getText();
            String shipcost = jTextField32.getText();

            Statement add_vendor = con.createStatement();
            add_vendor.executeQuery("Insert into Vendor values('"+VID+"','"+vName+"','"+address+"','"+email+"','"+phone+"','"+shipcost+"')");
            JOptionPane.showMessageDialog(this, " Insertion successful","Vendor has been inserted.", JOptionPane.INFORMATION_MESSAGE);
            tableload(vendoradd_table,"select * FROM vendor");

        }
        catch(SQLException se)
        {
            JOptionPane.showMessageDialog(this, "Database Insert Error","Unable to Insert into DB", JOptionPane.ERROR_MESSAGE);
        }
        catch(NumberFormatException e)
        {
            JOptionPane.showMessageDialog(this, "You have attempted to store blank or invalid numbers. Please enter valid numbers.",
                "Error", JOptionPane.ERROR_MESSAGE);
        }
        catch(NullPointerException npe)
        {
            JOptionPane.showMessageDialog(this, "A database connection was not properly established.",
                "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_save_btnActionPerformed

    private void clear_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clear_btnActionPerformed
        jTextField40.setText("");
        jTextField50.setText("");
        jTextField29.setText("");
        jTextField30.setText("");
        jTextField31.setText("");
        jTextField32.setText("");
        jTextField33.setText("");
    }//GEN-LAST:event_clear_btnActionPerformed

    private void jTextField36ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField36ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField36ActionPerformed

    private void searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchActionPerformed
        String key = jTextField40.getText();
        String search = "select vendorID,vendor_name,shipcost,address,email,telephone FROM vendor "
        +"where vendorID LIKE '%"+key+"%'";
        try {
            pst = con.prepareStatement(search);
            rs = pst.executeQuery();
            vendoradd_table.setModel(DbUtils.resultSetToTableModel(rs));

        }
        catch(NullPointerException npe)
        {
            JOptionPane.showMessageDialog(this, "A database connection was not properly established.",
                "Error", JOptionPane.ERROR_MESSAGE);
        }
        catch(SQLException se)
        {
            JOptionPane.showMessageDialog(this, "An error occurred while writing the financial report to the database.",
                "Error", JOptionPane.ERROR_MESSAGE);
        }
        tableload(vendoradd_table,"select * FROM vendor");
    }//GEN-LAST:event_searchActionPerformed

    private void reset_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reset_btnActionPerformed
        jTextField33.setText("");
        jTextField34.setText("");
        jTextField35.setText("");
        jTextField36.setText("");
        jTextField37.setText("");
        jTextField38.setText("");
    }//GEN-LAST:event_reset_btnActionPerformed

    private void jTextField38ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField38ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField38ActionPerformed

    private void edit_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edit_btnActionPerformed

        try{
            String VID = jTextField38.getText();
            String vName = jTextField33.getText();
            String address = jTextField34.getText();
            String email = jTextField35.getText();
            String phone = jTextField36.getText();
            String shipcost = jTextField37.getText();

            Statement add_vendor = con.createStatement();

            add_vendor.execute("update Vendor set vName='"+vName+"',address='"+address+"',email='"+email+"',"
                + "phone='"+phone+"',shipcost='"+shipcost+"' where VID='"+VID+"'");
            JOptionPane.showMessageDialog(this, " Insertion successful","Vendor has been updated.", JOptionPane.INFORMATION_MESSAGE);
            tableload(vendoradd_table,"select * FROM vendor");
        }
        catch(SQLException se)
        {
            JOptionPane.showMessageDialog(this, " Database Insert Error","Unable to update DB", JOptionPane.ERROR_MESSAGE);
        }
        catch(NumberFormatException e)
        {
            JOptionPane.showMessageDialog(this, "You have attempted to store blank or invalid numbers. Please enter valid numbers.",
                "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_edit_btnActionPerformed

    private void clear_btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clear_btn1ActionPerformed
        jTextField33.setEditable(true);
        jTextField34.setEditable(true);
        jTextField35.setEditable(true);
        jTextField36.setEditable(true);
        jTextField37.setEditable(true);
    }//GEN-LAST:event_clear_btn1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel addvendor;
    private javax.swing.JButton clear_btn;
    private javax.swing.JButton clear_btn1;
    private javax.swing.JButton edit_btn;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField29;
    private javax.swing.JTextField jTextField30;
    private javax.swing.JTextField jTextField31;
    private javax.swing.JTextField jTextField32;
    private javax.swing.JTextField jTextField33;
    private javax.swing.JTextField jTextField34;
    private javax.swing.JTextField jTextField35;
    private javax.swing.JTextField jTextField36;
    private javax.swing.JTextField jTextField37;
    private javax.swing.JTextField jTextField38;
    private javax.swing.JTextField jTextField40;
    private javax.swing.JTextField jTextField50;
    private javax.swing.JButton print;
    private javax.swing.JButton reset_btn;
    private javax.swing.JButton save_btn;
    private javax.swing.JButton search;
    private javax.swing.JTable vendoradd_table;
    // End of variables declaration//GEN-END:variables
}
