/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package itpshnew.sales;

import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author isira
 */
public class Purchase extends javax.swing.JPanel {

    private Connection conn = null;
    private PreparedStatement pst = null;
    private ResultSet rs = null;
    private boolean loaded = false;
    /**
     * Creates new form Purchase
     */
    public Purchase() {
        initComponents();
    }

    public void pubInit()
    {
        initComponents();
        loaded = true;
    }
    
    public boolean getLoaded()
    {
        return loaded;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        purchase_panel = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        sales_bill_num = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        itemid_box = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        itemname_box = new javax.swing.JTextField();
        additem_btn = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        newcus_btn = new javax.swing.JButton();
        searchcus_btn = new javax.swing.JButton();
        purchase_cusid_box = new javax.swing.JTextField();
        purchase_cusname_box = new javax.swing.JTextField();
        purchase_connum_box = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        purchase_table = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        jTextField10 = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jTextField11 = new javax.swing.JTextField();
        jTextField12 = new javax.swing.JTextField();
        jTextField13 = new javax.swing.JTextField();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        purchase_save_btn = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        remove_tablerow_btn = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();

        purchase_panel.setBackground(new java.awt.Color(202, 254, 227));
        purchase_panel.setToolTipText("");
        purchase_panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(100, 199, 150));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setText("Sales bill number");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 15, -1, -1));

        sales_bill_num.setEditable(false);
        sales_bill_num.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        sales_bill_num.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sales_bill_numActionPerformed(evt);
            }
        });
        jPanel2.add(sales_bill_num, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 10, 160, 35));

        jLabel3.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jLabel3.setText("Item ID");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        itemid_box.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        itemid_box.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemid_boxActionPerformed(evt);
            }
        });
        jPanel2.add(itemid_box, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 60, 230, 25));

        jLabel4.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jLabel4.setText("Item Name");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, -1));

        itemname_box.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        itemname_box.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemname_boxActionPerformed(evt);
            }
        });
        jPanel2.add(itemname_box, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 100, 230, 25));

        additem_btn.setBackground(new java.awt.Color(31, 233, 133));
        additem_btn.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        additem_btn.setText("Add");
        additem_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                additem_btnActionPerformed(evt);
            }
        });
        jPanel2.add(additem_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 140, 110, 35));

        jButton2.setBackground(new java.awt.Color(31, 233, 133));
        jButton2.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jButton2.setText("Clear");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 140, 110, 35));

        purchase_panel.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 510, 190));

        jPanel3.setBackground(new java.awt.Color(100, 199, 150));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Segoe UI Semibold", 0, 24)); // NOI18N
        jLabel5.setText("Customer");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 13, 130, 30));

        jLabel7.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jLabel7.setText("Customer ID");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jLabel8.setText("Customer Name");
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, -1, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jLabel9.setText("Contact Number");
        jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, -1, -1));

        newcus_btn.setBackground(new java.awt.Color(31, 233, 133));
        newcus_btn.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        newcus_btn.setText("New");
        newcus_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newcus_btnActionPerformed(evt);
            }
        });
        jPanel3.add(newcus_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 10, 100, 30));

        searchcus_btn.setBackground(new java.awt.Color(31, 233, 133));
        searchcus_btn.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        searchcus_btn.setText("Search");
        searchcus_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchcus_btnActionPerformed(evt);
            }
        });
        jPanel3.add(searchcus_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 10, 100, 30));

        purchase_cusid_box.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        purchase_cusid_box.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                purchase_cusid_boxActionPerformed(evt);
            }
        });
        jPanel3.add(purchase_cusid_box, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 60, 230, -1));

        purchase_cusname_box.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel3.add(purchase_cusname_box, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 100, 230, -1));

        purchase_connum_box.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        purchase_connum_box.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                purchase_connum_boxActionPerformed(evt);
            }
        });
        jPanel3.add(purchase_connum_box, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 140, 230, -1));

        purchase_panel.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 20, 500, 190));

        purchase_table.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        purchase_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Item ID", "Item Name", "Brand", "Manu. date", "Warranty", "Discount", "Amount"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        purchase_table.setGridColor(new java.awt.Color(100, 199, 150));
        jScrollPane1.setViewportView(purchase_table);

        purchase_panel.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 1040, 190));

        jPanel4.setBackground(new java.awt.Color(100, 199, 150));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jLabel10.setText("Num of Items");
        jPanel4.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 140, -1));

        jLabel11.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jLabel11.setText("Loyalty Discount");
        jPanel4.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 150, 20));

        jLabel12.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jLabel12.setText("Special Discount");
        jPanel4.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, -1));

        jLabel13.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jLabel13.setText("Extra Charges");
        jPanel4.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, -1, -1));
        jPanel4.add(jTextField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 10, 220, 25));
        jPanel4.add(jTextField8, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 50, 220, 25));

        jTextField9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField9ActionPerformed(evt);
            }
        });
        jPanel4.add(jTextField9, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 90, 220, 25));
        jPanel4.add(jTextField10, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 130, 220, 25));

        purchase_panel.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 470, 510, 170));

        jPanel5.setBackground(new java.awt.Color(100, 199, 150));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel14.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jLabel14.setText("Payment Type");
        jPanel5.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        jLabel15.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jLabel15.setText("Total Amount");
        jPanel5.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, -1));

        jLabel16.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jLabel16.setText("Amount Paid");
        jPanel5.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, -1));

        jLabel17.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jLabel17.setText("Balance");
        jPanel5.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, -1, -1));

        jTextField11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField11ActionPerformed(evt);
            }
        });
        jPanel5.add(jTextField11, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 50, 220, 25));
        jPanel5.add(jTextField12, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 90, 220, 25));

        jTextField13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField13ActionPerformed(evt);
            }
        });
        jPanel5.add(jTextField13, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 130, 220, 25));

        jRadioButton1.setBackground(new java.awt.Color(100, 199, 150));
        jRadioButton1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jRadioButton1.setText("Cash");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });
        jPanel5.add(jRadioButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 10, -1, -1));

        jRadioButton2.setBackground(new java.awt.Color(100, 199, 150));
        jRadioButton2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jRadioButton2.setText("Credit Card");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });
        jPanel5.add(jRadioButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 10, -1, -1));

        purchase_panel.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 470, 490, 170));

        jButton1.setBackground(new java.awt.Color(48, 214, 48));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/itpshnew/images/icons8_Print_40px.png"))); // NOI18N
        jButton1.setText("  Print");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        purchase_panel.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 660, 200, 50));

        purchase_save_btn.setBackground(new java.awt.Color(48, 214, 48));
        purchase_save_btn.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        purchase_save_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/itpshnew/images/icons8_Save_40px.png"))); // NOI18N
        purchase_save_btn.setText("  Save");
        purchase_save_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                purchase_save_btnActionPerformed(evt);
            }
        });
        purchase_panel.add(purchase_save_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 660, 200, 50));

        jButton3.setBackground(new java.awt.Color(48, 214, 48));
        jButton3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/itpshnew/images/icons8_Reset_40px.png"))); // NOI18N
        jButton3.setText("  Reset");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        purchase_panel.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 660, 200, 50));

        remove_tablerow_btn.setBackground(new java.awt.Color(31, 233, 133));
        remove_tablerow_btn.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        remove_tablerow_btn.setText("Remove");
        remove_tablerow_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                remove_tablerow_btnActionPerformed(evt);
            }
        });
        purchase_panel.add(remove_tablerow_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 430, 100, 30));

        jButton9.setBackground(new java.awt.Color(31, 233, 133));
        jButton9.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jButton9.setText("Done");
        purchase_panel.add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 430, 100, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(purchase_panel, javax.swing.GroupLayout.PREFERRED_SIZE, 1076, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(purchase_panel, javax.swing.GroupLayout.PREFERRED_SIZE, 718, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void sales_bill_numActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sales_bill_numActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sales_bill_numActionPerformed

    private void itemid_boxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemid_boxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_itemid_boxActionPerformed

    private void itemname_boxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemname_boxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_itemname_boxActionPerformed

    private void additem_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_additem_btnActionPerformed

        if("".equals(itemname_box.getText()))
        {
            String itemid = itemid_box.getText();
            try
            {
                pst = conn.prepareStatement("SELECT item_code,item_name,brand,manufacture_date,"
                        + "warranty_period,discount,selling_price FROM item WHERE item_code LIKE '%"+itemid+"%'");
                rs = pst.executeQuery();
                //purchase_table.setModel(DbUtils.resultSetToTableModel(rs));
                //DefaultTableModel tabelrowadd = (DefaultTableModel) purchase_table.getModel();
                //tabelrowadd.addRow(new Object[] {DbUtils.resultSetToTableModel(rs)});
            }
            catch (SQLException e1)
            {
                JOptionPane.showMessageDialog(null, "Invalid item ID", "Error", JOptionPane.ERROR_MESSAGE);
            }
            //purchase_table.setModel(DbUtils.resultSetToTableModel(rs));
        }
        else if("".equals(itemid_box.getText()))
        {
            String itemname = itemname_box.getText();
            try
            {
                pst = conn.prepareStatement("SELECT item_code,item_name,brand,manufacture_date,warranty_period,discount,selling_price FROM item WHERE item_name LIKE '%"+itemname+"%'");
                rs = pst.executeQuery();
                //purchase_table.setModel(DbUtils.resultSetToTableModel(rs));

                //DefaultTableModel tabelrowadd = (DefaultTableModel) purchase_table.getModel();
                //tabelrowadd.addRow(new Object[] {DbUtils.resultSetToTableModel(rs)});
            }
            catch (SQLException e1)
            {
                JOptionPane.showMessageDialog(null, "invalid item_name");
            }
        }

        //purchase_table.setModel(DbUtils.resultSetToTableModel(rs));

        //DefaultTableModel tabelrowadd = (DefaultTableModel) purchase_table.getModel();
        //tabelrowadd.addRow(new Object[] {DbUtils.resultSetToTableModel(rs)});
        purchase_table.setModel(DbUtils.resultSetToTableModel(rs));
        DefaultTableModel tabelrow = (DefaultTableModel) purchase_table.getModel(); //get selected row index

        int rowindex = purchase_table.getRowCount();
        rowindex++;

        // DefaultTableModel tabelrowadd = (DefaultTableModel) purchase_table.getModel();
        //tabelrowadd.addRow(new Object[] {DbUtils.resultSetToTableModel(rs)});

    }//GEN-LAST:event_additem_btnActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        itemid_box.setText("");
        itemname_box.setText("");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void newcus_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newcus_btnActionPerformed
        new newcus().setVisible(true);
        //this.setOpacity(0.5f);
        //com.sun.awt.AWTUtilities.setWindowOpacity(this, 0.5f); // change the opacity level of main frame
    }//GEN-LAST:event_newcus_btnActionPerformed

    private void searchcus_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchcus_btnActionPerformed
        new searchcus().setVisible(true);
        //this.setOpacity(0.5f);
        //com.sun.awt.AWTUtilities.setWindowOpacity(this, 0.5f); // change the opacity level of main frame
    }//GEN-LAST:event_searchcus_btnActionPerformed

    private void purchase_cusid_boxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_purchase_cusid_boxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_purchase_cusid_boxActionPerformed

    private void purchase_connum_boxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_purchase_connum_boxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_purchase_connum_boxActionPerformed

    private void jTextField9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField9ActionPerformed

    private void jTextField11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField11ActionPerformed

    private void jTextField13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField13ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField13ActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void purchase_save_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_purchase_save_btnActionPerformed
        //set bill number
        sales_bill_num.setText(new bill_class().bill_num_increment());
    }//GEN-LAST:event_purchase_save_btnActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void remove_tablerow_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_remove_tablerow_btnActionPerformed
        DefaultTableModel tableRow = (DefaultTableModel) purchase_table.getModel(); //get selected row index
        try
        {
            tableRow.removeRow(purchase_table.getSelectedRow());
        }
        catch (ArrayIndexOutOfBoundsException e)
        {
            JOptionPane.showMessageDialog(null,"You need to click a row.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_remove_tablerow_btnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton additem_btn;
    private javax.swing.JTextField itemid_box;
    private javax.swing.JTextField itemname_box;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JButton newcus_btn;
    public static javax.swing.JTextField purchase_connum_box;
    public static javax.swing.JTextField purchase_cusid_box;
    public static javax.swing.JTextField purchase_cusname_box;
    private javax.swing.JPanel purchase_panel;
    private javax.swing.JButton purchase_save_btn;
    private javax.swing.JTable purchase_table;
    private javax.swing.JButton remove_tablerow_btn;
    private javax.swing.JTextField sales_bill_num;
    private javax.swing.JButton searchcus_btn;
    // End of variables declaration//GEN-END:variables
}
